dev-install: Add a command_not_found_handle to bashrc
When a user types a command which is known to be provided by the
developer tools, let's help them out and guide them to typing
"dev_install" to get what they need.

BUG=b:264928672
TEST=on betty, base image (via VNC)
     type "vim somefile.txt"
     ~> get message about developer tools
     type "notacommand"
     ~> get the regular "command not found", no dev_install nag

Cq-Depend: chromium:4156631
Change-Id: I8a53493e5576d5fadd3cacfd2712de319acfe01b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/4156831
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Jack Rosenthal <jrosenth@chromium.org>
Tested-by: Jack Rosenthal <jrosenth@chromium.org>

diff --git a/dev-install/share/bashrc b/dev-install/share/bashrc
--- a/dev-install/share/bashrc
+++ b/dev-install/share/bashrc
@@ -6,3 +6,17 @@
 # active LD_LIBRARY_PATH settings.
 # https://crbug.com/535771
 alias sudo='sudo LD_LIBRARY_PATH="${LD_LIBRARY_PATH}"'
+
+# Hook to notify users of dev_install if they type a command which is
+# provided by running dev_install.
+command_not_found_handle() {
+  echo "${0##*/}: $1: command not found" >&2
+
+  if grep -Fxq "$1" /usr/share/dev-install/installable_commands; then
+    echo >&2
+    echo 'This command is available in the ChromiumOS developer tools.  You' >&2
+    echo 'can download the developer tools by running "sudo dev_install".' >&2
+  fi
+
+  return 127
+}
