init: Dump rollback-prefixed pstore on reboot
Firmware updates may ask for a reboot before starting ui. To support
enterprise rollback, which stores its data secret in pstore across a
reboot, dump rollback contents of pstore on fw update reboot.

Add a new reboot reason "firmware-update" to identify reboots that
update firmware and happen during system startup.

BUG=b:306656848
TEST=(with config that fakes fw reboot on flag file below)
touch /mnt/stateful_partition/fake_fw_reboot
echo "asd" > /dev/pmsg0
echo "rollback secret_key" > /dev/pmsg0
echo "test" > /dev/pmsg0
reboot
cat /sys/fs/pstore/pmsg-ramoops-0
  pmsg-key=<redacted - long string>
  rollback secret_key

Change-Id: I891145ef03a4b8769a80884aa7786ad4be94c98d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/5038715
Tested-by: Miriam Polzer <mpolzer@google.com>
Reviewed-by: Brian Norris <briannorris@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Miriam Polzer <mpolzer@google.com>

diff --git a/init/chromeos_shutdown b/init/chromeos_shutdown
--- a/init/chromeos_shutdown
+++ b/init/chromeos_shutdown
@@ -198,6 +198,29 @@ rm -rf /var/log/metrics/shutdown.*
 # Measure shutdown time up to this point.
 bootstat_archive "/var/log/metrics/shutdown.$(date --utc '+%Y%m%d%H%M%S')"
 
+# Preserves the rollback-prefixed content of pstore across one warm reboot.
+preserve_rollback_key() {
+  local pmsg="/dev/pmsg0"
+  local key f
+  for f in /sys/fs/pstore/pmsg-ramoops-*; do
+    # The glob may not match any file.
+    [ -e "${f}" ] || continue
+
+    # Ignore failures.
+    key="$(grep "^rollback " "${f}")" || continue
+    echo "${key}" >>"${pmsg}" || true
+
+    # We've found a key. We're done.
+    break
+  done
+}
+
+# Preserve rollback key across firmware update reboot.
+# shellcheck disable=SC2154
+if [ "${SHUTDOWN_REASON}" = "firmware-update" ]; then
+  preserve_rollback_key
+fi
+
 # To be safe, flush buffers to disk again before unmounting. (From
 # https://crbug.com/760007 it seems that a failed umount can get the filesystem
 # into a state that renders a subsequent sync ineffective.)
