update_engine: fix some bashisms
The `[` command only supports `=`, never `==`.
Tweak the code to address some linting warnings.

BUG=None
TEST=`cros lint` doesn't complain about it

Change-Id: If2fbcdd78d827863d588a267675b65366f257696
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/5527812
Auto-Submit: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Jae Hoon Kim <kimjae@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Jae Hoon Kim <kimjae@chromium.org>

diff --git a/update_engine/run_unittests b/update_engine/run_unittests
--- a/update_engine/run_unittests
+++ b/update_engine/run_unittests
@@ -16,7 +16,7 @@ user_pass=0
 root_pass=0
 sudo ./update_engine_unittests --gtest_filter='*.RunAsRoot*' && root_pass=1
 
-echo -n "User tests: " && [ $user_pass == 1 ] && echo "PASSED" || echo "FAILED"
-echo -n "Root tests: " && [ $root_pass == 1 ] && echo "PASSED" || echo "FAILED"
+printf "User tests: "; [ "${user_pass}" = 1 ] && echo "PASSED" || echo "FAILED"
+printf "Root tests: "; [ "${root_pass}" = 1 ] && echo "PASSED" || echo "FAILED"
 
 exit $((2 - user_pass - root_pass))
