dlcservice: Implement logical volume based DLC [un]packer
This patchset streamlines DLC image handling by directly integrating
with the dlcservice daemon to ensure the deploy flow stays synchronized
with the latest DLC state.

Additionally, it prioritizes the deploy flow over dlctool for rolling
and unrolling DLC locations, resulting in improved efficiency and
reduced error potential. Even less future maintenance.

BUG=b:322286126
TEST=dlctool [--unpack] --id=<ID> <PATH>

Change-Id: I9525973a7bfd6add6fb5ebe4ec2baab4dbe41dcc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/5236008
Tested-by: Jae Hoon Kim <kimjae@chromium.org>
Reviewed-by: Yuanpeng Ni‎ <yuanpengni@chromium.org>
Commit-Queue: Jae Hoon Kim <kimjae@chromium.org>

diff --git a/dlcservice/tools/dlctool b/dlcservice/tools/dlctool
--- a/dlcservice/tools/dlctool
+++ b/dlcservice/tools/dlctool
@@ -4,25 +4,25 @@
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
-# TODO(b/235407459): Fix all lints/migrate over to C++.
+# TODO(b/227476869): Fix all lints/migrate over to C++/file a new bug.
 . /usr/share/misc/chromeos-common.sh || exit 1
 . /usr/sbin/write_gpt.sh || exit 1
 . /usr/share/misc/shflags || exit 1
 
 # Constant variables related to dlcservice.
 readonly BLOCK_SIZE=4096
-readonly DLC_CACHE_PATH="/var/cache/dlc"
 readonly DLC_HASHTREE_FILE="hashtree"
 readonly DLC_IMG_FILE="dlc.img"
-readonly DLC_LIB_PATH="/var/lib/dlcservice/dlc"
 readonly DLC_METADATA_PATH="/opt/google/dlc"
 readonly DLC_PACKAGE="package"
 readonly DLC_PRELOAD_PATH="/var/cache/dlc-images"
-readonly DLC_SLOT_A="dlc_a"
-readonly DLC_SLOT_B="dlc_b"
 readonly DLC_TABLE_FILE="table"
 readonly IMAGELOADER_JSON_FILE="imageloader.json"
 readonly MOUNT_PATH="/run/imageloader"
+readonly STATEFUL_PATH="/mnt/stateful_partition"
+
+# Define later in order.
+readonly DLC_DEPLOY_PATH="${STATEFUL_PATH}/unencrypted/dlc-deployed-images"
 
 # Command line parsing variables.
 readonly FLAGS_HELP="Usage:
@@ -76,23 +76,54 @@ path_exists() {
   [[ -f "${path}" || -d "${path}" ]]
 }
 
+# Check if the DLC is installed.
+is_dlc_installed() {
+  local state
+  state=$(dlcservice_util --dlc_state --id="${FLAGS_id}" | jq ".state")
+  [ "${state}" == 2 ]
+}
+
 # Check if the DLC is preloadable.
 is_dlc_preloadable() {
   [ -f "${DLC_PRELOAD_PATH}/${FLAGS_id}/${DLC_PACKAGE}/${DLC_IMG_FILE}" ]
 }
 
-# Locate the active DLC image from cache.
-locate_dlc_image() {
-  load_base_vars
-  local root_part=$(get_partition_number $(rootdev -s))
-  local dlc_cache_path="${DLC_CACHE_PATH}/${FLAGS_id}/${DLC_PACKAGE}"
-  if [[ "${root_part}" == "${PARTITION_NUM_ROOT_A}" ]]; then
-    echo "${dlc_cache_path}/${DLC_SLOT_A}/${DLC_IMG_FILE}"
-  elif [[ "${root_part}" == "${PARTITION_NUM_ROOT_B}" ]]; then
-    echo "${dlc_cache_path}/${DLC_SLOT_B}/${DLC_IMG_FILE}"
-  else
-    die "Unexpected root partition ${root_part}"
+# Check if the DLC is scaled.
+is_dlc_scaled() {
+  dlc_metadata_util --get --id="${FLAGS_id}" | jq ".manifest.scaled"
+}
+
+# Get DLC image path.
+dlc_image_path() {
+  dlcservice_util --dlc_state --id="${FLAGS_id}" | jq -r ".image_path"
+}
+
+# Try installing the DLC if required.
+try_installing_dlc() {
+  if is_dlc_installed; then
+    echo "DLC is already installed, continuing.."
+    return
   fi
+
+  local err_msg
+  local inst_cmd
+  inst_cmd="dlcservice_util --install --id=${FLAGS_id}"
+  if is_dlc_preloadable; then
+    echo "Preloading DLC to not override deployed DLC images."
+    eval "${inst_cmd}" || die "Failed to preload."
+    return
+  fi
+  if is_dlc_scaled; then
+    echo "Trying to install DLC because it's scaled."
+    eval "${inst_cmd}" || die "Failed to install scaled."
+    return
+  fi
+  if is_dlc_force_ota; then
+    echo "Trying to install DLC because it's force-ota."
+    eval "${inst_cmd}" || die "Failed to install force-ota."
+    return
+  fi
+  die "Can't install the DLC."
 }
 
 # Unpack (unsquashfs) the DLC image.
@@ -101,12 +132,8 @@ unpack_dlc() {
   if path_exists "${DIR_NAME}"; then
     die "${DIR_NAME} is a path which already exists."
   fi
-  # If the DLC is preloadable, install it.
-  if is_dlc_preloadable; then
-    echo "Preloading DLC to not override deployed DLC images."
-    dlcservice_util --install --id="${FLAGS_id}" || die "Failed to preload."
-  fi
-  unsquashfs -d "${DIR_NAME}" $(locate_dlc_image) || die "Failed to unpack."
+  try_installing_dlc || die "Failed installing DLC prior to unpack."
+  unsquashfs -d "${DIR_NAME}" "$(dlc_image_path)" || die "Failed to unpack."
 }
 
 # Checks to see if the rootfs is writable.
@@ -119,11 +146,10 @@ check_writable_rootfs() {
   fi
 }
 
-# Unmount and delete a DLC by force.
+# Unmount and delete a DLC.
 force_delete() {
   imageloader --unmount --mount_point="${MOUNT_PATH}/${FLAGS_id}/${DLC_PACKAGE}"
-  rm -rf "${DLC_CACHE_PATH}/${FLAGS_id}" "${DLC_LIB_PATH}/${FLAGS_id}" \
-    "${DLC_PRELOAD_PATH}/${FLAGS_id}"
+  dlcservice_util --uninstall --id="${FLAGS_id}"
 }
 
 # Check if the directory can be packed as DLC image.
@@ -261,16 +287,16 @@ write_metadata_to_rootfs() {
 
 # Writes the DLC image to dlcservice cache.
 write_dlc_image() {
-  local cache_path="${DLC_CACHE_PATH}/${FLAGS_id}/${DLC_PACKAGE}"
-  local cache_path_A="${cache_path}/dlc_a"
-  local cache_path_B="${cache_path}/dlc_b"
-  mkdir -p "${cache_path_A}" "${cache_path_B}"
-  echo "${cache_path_A}" "${cache_path_B}" | xargs -n 1 cp "${DLC_IMG_FILE}"
+  mkdir -p "${DLC_DEPLOY_PATH}/${FLAGS_id}/${DLC_PACKAGE}/"
+  cp "${DLC_IMG_FILE}" "${DLC_DEPLOY_PATH}/${FLAGS_id}/${DLC_PACKAGE}/"
 }
 
-# Changes ownership for paths/files in dlcservice cache.
+# Changes permissions and ownership for DLC paths/files.
 update_cache() {
-  chown -R dlcservice:dlcservice "${DLC_CACHE_PATH}/${FLAGS_id}"
+  local p
+  p="${DLC_DEPLOY_PATH}/${FLAGS_id}"
+  chmod -R 0755 "${p}"
+  chown -R dlcservice:dlcservice "${p}"
 }
 
 deploy_dlc() {
@@ -309,23 +335,21 @@ main() {
   echo "Packing DLC (${FLAGS_id}) from: ${DIR_NAME}"
   check_writable_rootfs
 
-  echo "Stopping imageloader"
-  stop imageloader
-
-  echo "Stopping dlcservice"
-  stop dlcservice
-
   echo "Force deleting ${FLAGS_id}"
   force_delete
 
   echo "Creating DLC from: ${DIR_NAME}"
   deploy_dlc
 
+  # Explicit stop and start, restart isn't as fresh.
+  echo "Stopping dlcservice"
+  stop dlcservice
+
   echo "Starting dlcservice"
   start dlcservice && sleep 1
 
-  # Install the new DLC image.
-  dlcservice_util --install --id="${FLAGS_id}" || die "Failed to install"
+  # Install (deploy) the new DLC image.
+  dlcservice_util --deploy --id="${FLAGS_id}" || die "Failed to install."
 }
 
 check_flags
