power: Remove hibernate support
hibernate is not moving forward for now

BUG=b:330187315
TEST=FEATURES=test emerge-brya power_manager
  cd power_manager
  git grep -i hibernate
    => no results

Change-Id: I460634a46014a100d4a2a4abb02cb8957ff6e12c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/5381270
Tested-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-by: Brian Geffon <bgeffon@chromium.org>
Commit-Queue: Matthias Kaehlcke <mka@chromium.org>
Reviewed-by: Mengqi Guo <mqg@chromium.org>
Reviewed-by: Jesse McGuire <jessemcguire@google.com>

diff --git a/power_manager/powerd/powerd_suspend b/power_manager/powerd/powerd_suspend
--- a/power_manager/powerd/powerd_suspend
+++ b/power_manager/powerd/powerd_suspend
@@ -13,8 +13,6 @@ DEFINE_integer wakeup_count -1 \
   "wakeup event count from start of suspend. -1 to disable" w
 DEFINE_boolean suspend_to_idle false \
   "indicates that the system should suspend to idle (freeze)" i
-DEFINE_boolean suspend_to_disk false \
-  "indicates that the system should suspend to disk (hibernate)" d
 
 # Exit codes returned by this script and reported via the
 # Power.SuspendResult histogram:
@@ -55,10 +53,6 @@ readonly POWER_STATUS_ON_SUSPEND_FILE="${ROOT_RUN_DIR}"/power-status-on-suspend
 # send_metrics_on_resume and read by autotests; doesn't need to persist
 # across reboots.
 readonly LAST_RESUME_TIMINGS_FILE="${ROOT_RUN_DIR}"/last_resume_timings
-
-# File whose presence indicates that the system should reboot after a successful
-# hibernation instead of shutting down.
-readonly REBOOT_AFTER_HIBERNATE_FILE="${ROOT_RUN_DIR}"/reboot_after_hibernate
 
 # Directory where this script (running as root) writes files that must
 # persist across reboots.
@@ -244,14 +238,9 @@ eval set -- "${FLAGS_ARGV}"
 # (http://crbug.com/338015).
 metrics_client -e Power.SuspendAttempt 0 2 &
 
-# Don't log the suspend time when hibernating, otherwise the
-# Power.TimeInSuspendAtResume metric would include hibernations,
-# which would be misleading.
-if [ "${FLAGS_suspend_to_disk}" -eq "${FLAGS_FALSE}" ]; then
-  # Log the time before going to suspend (no-op if no RTC).
-  cp /sys/class/rtc/rtc0/since_epoch "${SUSPEND_TO_RAM_TIME_FILE}" \
-    2> /dev/null || true
-fi
+# Log the time before going to suspend (no-op if no RTC).
+cp /sys/class/rtc/rtc0/since_epoch "${SUSPEND_TO_RAM_TIME_FILE}" \
+  2> /dev/null || true
 
 # Remove last_resume_timings to ensure the file is fresh on resume.
 rm -f "${LAST_RESUME_TIMINGS_FILE}"
@@ -301,31 +290,17 @@ else
     /sbin/hwclock -V > /dev/null
   fi
 
-  # For hibernate, invoke the hiberman helper process to take us all the way
-  # down.
-  if [ "${FLAGS_suspend_to_disk}" -eq 0 ]; then
-    reboot_flag=""
-
-    if [ -e "${REBOOT_AFTER_HIBERNATE_FILE}" ]; then
-      reboot_flag="-r"
-    fi
-
-    error="Failed to hibernate"
-    /sbin/minijail0 --config=/usr/share/minijail/hiberman.conf \
-        -- /usr/sbin/hiberman hibernate "${reboot_flag}"
-  else
-    # Echo freeze to /sys/power/state on platforms that support suspend to idle.
-    action='mem'
-    if [ "${FLAGS_suspend_to_idle}" -eq 0 ]; then
-      action='freeze'
-      unbind_igb_devices
-    fi
-
-    # Suspend. This is piped through cat since we want to determine
-    # the causes of failures -- dash's "echo" command appears to not print
-    # anything in response to write errors.
-    error=$( (printf '%s' "${action}" | cat > /sys/power/state) 2>&1)
+  # Echo freeze to /sys/power/state on platforms that support suspend to idle.
+  action='mem'
+  if [ "${FLAGS_suspend_to_idle}" -eq 0 ]; then
+    action='freeze'
+    unbind_igb_devices
   fi
+
+  # Suspend. This is piped through cat since we want to determine
+  # the causes of failures -- dash's "echo" command appears to not print
+  # anything in response to write errors.
+  error=$( (printf '%s' "${action}" | cat > /sys/power/state) 2>&1)
 
   if [ $? -eq 0 ]; then
     # On resume:
