vm_tools: refvm: Adjust installation process
* Reduce disk layout to fit within 10GB disks
* Start installer in .profile
* Added interactive mode to installer
* Require confirmation before shutting down in interactive mode
* Drop to a shell on install failure in interactive mode

BUG=b:281772103
TEST=Install refvm with vmc start

Change-Id: Ifa42543a5dba49d8a0fab49666198e6a335ab067
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/4619429
Commit-Queue: James Ye <jamesye@google.com>
Reviewed-by: Fergus Dall <sidereal@google.com>
Tested-by: kokoro <noreply+kokoro@google.com>

diff --git a/vm_tools/reference_vm/data/usr/local/bin/install-refvm b/vm_tools/reference_vm/data/usr/local/bin/install-refvm
--- a/vm_tools/reference_vm/data/usr/local/bin/install-refvm
+++ b/vm_tools/reference_vm/data/usr/local/bin/install-refvm
@@ -14,6 +14,40 @@ TARGET="${TMPDIR}/target"
 mkdir -p "${TMPDIR}"
 export TMPDIR
 
+interactive=true
+if dmidecode -t 11 -q | grep -q refvm:noninteractive=true; then
+  interactive=false
+fi
+
+success=false
+
+end_install() {
+  # Cleanup
+  if [[ -e "/dev/${src_vg}/root-snap" ]]; then
+    lvremove -y "/dev/${src_vg}/root-snap"
+  fi
+  journalctl --flush
+  umount -q /etc/lvm || true
+
+  if [[ "${success}" == true ]]; then
+    echo "Installation successful."
+  else
+    echo "Installation failed."
+  fi
+
+  if [[ "${interactive}" == true && "${success}" == false ]]; then
+    echo "Starting a shell for debugging."
+    exec bash
+  fi
+
+  if [[ "${interactive}" == true ]]; then
+    read -r -p "Press ENTER to shut down the installer."
+  fi
+
+  systemctl poweroff
+}
+trap end_install EXIT
+
 # Avoid logging to disk during installation.
 journalctl --relinquish-var
 
@@ -85,13 +119,6 @@ chroot "${TARGET}" grub-install --uefi-secure-boot
 chroot "${TARGET}" update-grub
 chroot "${TARGET}" update-initramfs -u
 
-# Cleanup
 umount -R "${TARGET}"
-if [[ "${src_lv}" == "root-snap" ]]; then
-  lvremove -y "/dev/${src_vg}/root-snap"
-fi
-journalctl --flush
-umount -q /etc/lvm || true
 
-echo "Installation successful"
-systemctl poweroff
+success=true
