bootstat: Drop awk redirection / error handling
Redirection is disabled in our unconditionally-sandboxed mawk:
https://crbug.com/767182

And ERRNO is not even in POSIX (nor 'mawk'), so this doesn't work at
all. (See also https://crrev.com/c/4139193.)

Just elevate the intended error handling to shell instead.

BUG=none
TEST=bootstat_summary on a base image (i.e., no gawk)
TEST=`sudo -u chronos -g chronos bootstat_summary` with an unreadable
     /tmp/uptime-foo and no /usr/local/bin/awk->gawk

Change-Id: I5d9c1c265bd7e7585a55a861829a076deda265b5
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/4137207
Reviewed-by: Hidehiko Abe <hidehiko@chromium.org>
Tested-by: Brian Norris <briannorris@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Brian Norris <briannorris@chromium.org>

diff --git a/bootstat/bootstat_summary b/bootstat/bootstat_summary
--- a/bootstat/bootstat_summary
+++ b/bootstat/bootstat_summary
@@ -43,7 +43,6 @@ SUMMARIZE_TIME='
 
 # If there are no arguments on the command line, summarize all the
 # events.  If there are arguments, summarize only the named events.
-# Error checking is deliberately minimal, to keep this script simple.
 if [ $# -eq 0 ]; then
   set -- "${FLAGS_directory}/uptime-"*
 else
@@ -55,19 +54,24 @@ else
   done
 fi
 
+max=$#
+i=0
+# Catch some basic errors so awk doesn't choke.
+while [ $((i += 1)) -le "${max}" ]; do
+  if [ -r "$1" ]; then
+    set -- "$@" "$1"
+  else
+    echo "Error: file $1 is not readable" 1>&2
+  fi
+  shift
+done
+
 # Pipeline explained:
 #  1st awk program: print times as milliseconds and normalize idle time
 #     by NCPU.
 #  sort: sort the events by the uptime timestamp.
 #  sed: remove '/tmp/uptime-' from the event name.
 #  2nd awk program:  produce the summarized output
-awk 'BEGINFILE {
-       # Ignore file errors.
-       if (ERRNO != "") {
-         print "Error reading file", FILENAME, ERRNO > "/dev/stderr"
-         nextfile
-       }
-     }
-     BEGIN{OFMT="%f"}
+awk 'BEGIN{OFMT="%f"}
      {print 1000*$1, 1000*$2/'"${NCPU}"', FILENAME}' "$@" |
   sort -k 1n | sed 's=[^ ]*uptime-==' | awk "${SUMMARIZE_TIME}"
