vm_tools: Fix upgrade_container on apt
--allow-releaseinfo-change isn't supported in Stretch's version of apt,
add a fallback for that case.

BUG=b:279841814
TEST=sudo ./upgrade_container DEBIAN_BUSTER DEBIAN_BULLSEYE

Change-Id: I0280dc86d6718b1d2c98eefe136df157c78c3300
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/4583195
Reviewed-by: James Ye <jamesye@google.com>
Commit-Queue: David Munro <davidmunro@google.com>
Tested-by: David Munro <davidmunro@google.com>
Reviewed-by: Fergus Dall <sidereal@google.com>

diff --git a/vm_tools/upgrade_container/upgrade_container b/vm_tools/upgrade_container/upgrade_container
--- a/vm_tools/upgrade_container/upgrade_container
+++ b/vm_tools/upgrade_container/upgrade_container
@@ -69,7 +69,14 @@ do_upgrade() {
   dpkg --configure -a || true
 
   # Upgrade everything.
-  apt-get ${APT_OPTIONS} update -y --allow-releaseinfo-change
+  # --allow-releaseinfo-change was only added in buster, so if it fails try
+  # again without the argument in case we're on stretch.  We try this way
+  # instead of checking lsb-release or similar in case a failed upgrade leaves
+  # them with modified release info but old apt. They'll probably hit other
+  # issues if that's the case, but might as well try.
+  if ! apt-get ${APT_OPTIONS} update -y --allow-releaseinfo-change; then
+    apt-get ${APT_OPTIONS} update -y
+  fi
   apt-get ${APT_OPTIONS} upgrade -y
   apt-get ${APT_OPTIONS} dist-upgrade -y
 }
