power: cpufreq_config: add error handling
Missing or incorrect cpufreq governors are silently ignored today, which
can easily cause oversights.

NB: Gracefully catching "$?" is touchy; doing

  if ! <cmd>; then ... utilize $?; fi

is wrong, because the "!" will invert the status code. This is the
cleanest form I could come up with.

BUG=b:197685239
TEST=shellcheck
TEST=put bad entry in /etc/cpufreq.conf, `cpufreq_config; echo $?`;
     `start cpufreq` and check /var/log/upstart.log

Change-Id: I1426f5deb3fb799cb12d805d57938ce37e014499
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/3119128
Tested-by: Brian Norris <briannorris@chromium.org>
Commit-Queue: Brian Norris <briannorris@chromium.org>
Reviewed-by: Eric Caruso <ejcaruso@chromium.org>

diff --git a/power_manager/tools/cpufreq_config b/power_manager/tools/cpufreq_config
--- a/power_manager/tools/cpufreq_config
+++ b/power_manager/tools/cpufreq_config
@@ -11,6 +11,10 @@
 CPU_BASE_DIR=/sys/devices/system/cpu
 CPUFREQ_DIR="${CPU_BASE_DIR}/cpufreq"
 
+error() {
+  echo "$*" 1>&2
+}
+
 ##############################################
 # Sets the cpufreq governor for all CPUs.
 # Globals:
@@ -23,12 +27,18 @@ CPUFREQ_DIR="${CPU_BASE_DIR}/cpufreq"
 cpufreq_set_governor() {
   local governor="$1"
   local cpu
+  local ret=0
 
   for cpu in "${CPU_BASE_DIR}"/cpu[0-9]*; do
     if [ -e "${cpu}/cpufreq" ]; then
-      echo "${governor}" > "${cpu}/cpufreq/scaling_governor"
+      echo "${governor}" > "${cpu}/cpufreq/scaling_governor" || {
+        ret="$?"
+        error "Failed to set ${cpu} governor to ${governor}"
+      }
     fi
   done
+
+  return "${ret}"
 }
 
 ###########################################################################
@@ -129,12 +139,16 @@ interactive_policy_set_optional() {
 #########################################################################
 cpufreq_config_interactive() {
   local setting
+  local ret=0
 
   GOVERNOR_DIR="${CPUFREQ_DIR}/interactive"
   if [ -d "${GOVERNOR_DIR}" ]; then
     for setting in input_boost above_hispeed_delay go_hispeed_load \
         hispeed_freq min_sample_time target_loads timer_rate; do
-      governor_set_optional "${setting}"
+      governor_set_optional "${setting}" || {
+        ret="$?"
+        error "Failed to set interactive setting ${setting}"
+      }
     done
   else
     local p
@@ -143,10 +157,15 @@ cpufreq_config_interactive() {
 
       for setting in input_boost above_hispeed_delay go_hispeed_load \
           hispeed_freq min_sample_time target_loads timer_rate; do
-        interactive_policy_set_optional "${policy}" "${setting}"
+        interactive_policy_set_optional "${policy}" "${setting}" || {
+          ret="$?"
+          error "Failed to set interactive policy ${policy} to ${setting}"
+        }
       done
     done
   fi
+
+  return "${ret}"
 }
 
 
@@ -166,12 +185,18 @@ cpufreq_config_interactive() {
 #########################################################################
 cpufreq_config_ondemand() {
   local setting
+  local ret=0
 
   GOVERNOR_DIR="${CPUFREQ_DIR}/ondemand"
   for setting in sampling_rate up_threshold ignore_nice_load \
       io_is_busy sampling_down_factor powersave_bias; do
-    governor_set_optional "${setting}"
+    governor_set_optional "${setting}" || {
+      ret="$?"
+      error "Failed to set ondemand setting ${setting}"
+    }
   done
+
+  return "${ret}"
 }
 
 ######################################################################
@@ -180,6 +205,8 @@ if [ ! -f /etc/cpufreq.conf ]; then
   exit 0
 fi
 . /etc/cpufreq.conf
+
+ret=0
 
 if [ -z "${CPUFREQ_GOVERNOR}" ]; then
   if dump_power_status | grep -q 'battery_status Discharging'; then
@@ -193,15 +220,20 @@ if [ -z "${CPUFREQ_GOVERNOR}" ]; then
   exit 0
 fi
 
-cpufreq_set_governor "${CPUFREQ_GOVERNOR}"
+cpufreq_set_governor "${CPUFREQ_GOVERNOR}" || ret="$?"
 
 if [ "${CPUFREQ_GOVERNOR}" = "interactive" ]; then
   cpufreq_config_interactive
 elif [ "${CPUFREQ_GOVERNOR}" = "ondemand" ]; then
   cpufreq_config_ondemand
-fi
+fi || ret="$?"
 
 # Set SELinux contexts for the newly created files (if any)
 if [ -f /sys/fs/selinux/enforce ]; then
-  /sbin/restorecon -R "${CPUFREQ_DIR}"
+  /sbin/restorecon -R "${CPUFREQ_DIR}" || {
+    ret="$?"
+    error "restorecon failed"
+  }
 fi
+
+exit "${ret}"
