power: send_metrics_on_resume: Fix style issues
This bash script has many style issues, fix it. This change is a cosmetic
change, so the behavior should be the same.

BUG=None
TEST=tast run $DUT power.SuspendPerf

Change-Id: I7d444409d9f7a145d819209f40f1c58be1caf4eb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/5691512
Reviewed-by: Eizan Miyamoto <eizan@chromium.org>
Auto-Submit: Masami Hiramatsu <mhiramat@google.com>
Tested-by: Masami Hiramatsu <mhiramat@google.com>
Reviewed-by: Brian Norris <briannorris@chromium.org>
Commit-Queue: Masami Hiramatsu <mhiramat@google.com>

diff --git a/power_manager/tools/send_metrics_on_resume b/power_manager/tools/send_metrics_on_resume
--- a/power_manager/tools/send_metrics_on_resume
+++ b/power_manager/tools/send_metrics_on_resume
@@ -62,7 +62,7 @@ split_recent_messages() {
       break;
     fi
     retries=$((retries-1))
-    if [ $retries -eq 0 ]; then
+    if [ "${retries}" -eq 0 ]; then
       log_msg "Could not find end of resume indicator splitting messages"
       break # Skip cleanup and sleep steps and exit loop
     fi
@@ -79,8 +79,8 @@ cleanup_recent_messages() {
   [ -n "$1" ] || return
   local recent_messages="$1"
 
-  /bin/rm "$recent_messages"
-  /bin/rmdir "$(dirname "$recent_messages")"
+  /bin/rm "${recent_messages}"
+  /bin/rmdir "$(dirname "${recent_messages}")"
 }
 
 # Sends to UMA the total time since going in suspend:
@@ -90,22 +90,23 @@ cleanup_recent_messages() {
 #   $1 - wake-up event: Boot or Resume
 send_time_in_suspend() {
   [ -n "$1" ] || return
-  local time_in_suspend_name=Power.TimeInSuspendAt$1
+  local time_in_suspend_name=Power.TimeInSuspendAt"$1"
 
   # On suspend, powerd_suspend stores the current RTC value to a file.
-  local f_suspend_at=${root_spool_dir}/suspend-to-ram-time
-  [ -r $f_suspend_at ] || return
+  local f_suspend_at="${root_spool_dir}/suspend-to-ram-time"
+  [ -r "${f_suspend_at}" ] || return
 
   local resume_at
   resume_at=$(/bin/cat /sys/class/rtc/rtc0/since_epoch)
   local suspend_at
-  suspend_at=$(/bin/cat $f_suspend_at)
-  /bin/rm -f $f_suspend_at &
-  [ "$resume_at" -gt "$suspend_at" ] || return
+  suspend_at=$(/bin/cat "${f_suspend_at}")
+  /bin/rm -f "${f_suspend_at}" &
+  [ "${resume_at}" -gt "${suspend_at}" ] || return
 
   # Converts seconds to minutes rounding to the nearest whole minute.
   local time_in_suspend=$(((resume_at - suspend_at + 30) / 60))
-  /usr/bin/metrics_client "$time_in_suspend_name" $time_in_suspend 1 10000 50 &
+  /usr/bin/metrics_client "${time_in_suspend_name}" "${time_in_suspend}" \
+    1 10000 50 &
 }
 
 # Prints the firmware (just BIOS, not including EC) resume time in
@@ -122,11 +123,11 @@ calculate_firmware_resume_time() {
     }
     END {
       if (tsc_at_resume != 0) {
-        printf "%d", int(tsc_at_resume / '$cpu_freq')
+        printf "%d", int(tsc_at_resume / '"${cpu_freq}"')
       }
     }
   '
-  dmesg | awk "$AWK_PROG"
+  dmesg | awk "${AWK_PROG}"
 }
 
 # Prints the timestamp of the last occurrence of a specified string in
@@ -242,8 +243,8 @@ send_suspend_resume_time() {
   local recent_messages="$1"
 
   # On suspend, powerd_suspend stores the power status to a file.
-  local power_status_on_suspend=${root_run_dir}/power-status-on-suspend
-  [ -r $power_status_on_suspend ] || return
+  local power_status_on_suspend="${root_run_dir}/power-status-on-suspend"
+  [ -r "${power_status_on_suspend}" ] || return
 
   # Greps the timestamps.
   local start_suspend_time
@@ -251,49 +252,51 @@ send_suspend_resume_time() {
   local start_resume_time
   local end_resume_time
   local cpu_ready_time
-  start_suspend_time=$(get_start_suspend_time "$recent_messages")
-  end_suspend_time=$(get_end_suspend_time "$recent_messages")
-  start_resume_time=$(get_start_resume_time "$recent_messages")
-  end_resume_time=$(get_end_resume_time "$recent_messages")
-  cpu_ready_time=$(get_cpu_ready_time "$recent_messages")
-  log_metric start_suspend_time "$start_suspend_time"
-  log_metric end_suspend_time "$end_suspend_time"
-  log_metric start_resume_time "$start_resume_time"
-  log_metric end_resume_time "$end_resume_time"
-  log_metric cpu_ready_time "$cpu_ready_time"
+  start_suspend_time=$(get_start_suspend_time "${recent_messages}")
+  end_suspend_time=$(get_end_suspend_time "${recent_messages}")
+  start_resume_time=$(get_start_resume_time "${recent_messages}")
+  end_resume_time=$(get_end_resume_time "${recent_messages}")
+  cpu_ready_time=$(get_cpu_ready_time "${recent_messages}")
+  log_metric start_suspend_time "${start_suspend_time}"
+  log_metric end_suspend_time "${end_suspend_time}"
+  log_metric start_resume_time "${start_resume_time}"
+  log_metric end_resume_time "${end_resume_time}"
+  log_metric cpu_ready_time "${cpu_ready_time}"
 
-  [ -z "$start_suspend_time" ] && log_msg "Unable to get start_suspend_time"
-  [ -z "$start_resume_time" ] && log_msg "Unable to get start_resume_time"
-  [ -z "$end_resume_time" ] && log_msg "Unable to get end_resume_time"
+  [ -z "${start_suspend_time}" ] && log_msg "Unable to get start_suspend_time"
+  [ -z "${start_resume_time}" ] && log_msg "Unable to get start_resume_time"
+  [ -z "${end_resume_time}" ] && log_msg "Unable to get end_resume_time"
 
   # Calculates the time intervals in milliseconds.
-  [ -n "$start_suspend_time" ] && [ -n "$start_resume_time" ] &&
+  [ -n "${start_suspend_time}" ] && [ -n "${start_resume_time}" ] &&
     local kernel_suspend_time
-    kernel_suspend_time=$(echo "$start_suspend_time" "$start_resume_time" |
+    kernel_suspend_time=$(echo "${start_suspend_time}" "${start_resume_time}" |
     /usr/bin/awk '{ if (NF == 2 && $1 < $2) print int(($2 - $1) * 1000) }')
-  [ -n "$start_resume_time" ] && [ -n "$end_resume_time" ] &&
+  [ -n "${start_resume_time}" ] && [ -n "${end_resume_time}" ] &&
     local kernel_resume_time
-    kernel_resume_time=$(echo "$start_resume_time" "$end_resume_time" |
+    kernel_resume_time=$(echo "${start_resume_time}" "${end_resume_time}" |
     /usr/bin/awk '{ if (NF == 2 && $1 < $2) print int(($2 - $1) * 1000) }')
   local firmware_resume_time
   firmware_resume_time=$(calculate_firmware_resume_time)
 
-  [ -z "$firmware_resume_time" ] && log_msg "Unable to get firmware_resume_time"
+  [ -z "${firmware_resume_time}" ] && \
+    log_msg "Unable to get firmware_resume_time"
 
   # Sends the metrics. Uses the pre-suspend AC status for both suspend
   # and resume since this is the mode that most software is configured
   # at at resume time.
   local ac_status
-  ac_status=$(/bin/cat $power_status_on_suspend)
-  [ -n "$kernel_suspend_time" ] && /usr/bin/metrics_client \
-    Power.KernelSuspendTime"$ac_status" "$kernel_suspend_time" 1 10000 50 &
-  [ -n "$kernel_resume_time" ] && /usr/bin/metrics_client \
-    Power.KernelResumeTime"$ac_status" "$kernel_resume_time" 1 10000 50 &
-  [ -n "$firmware_resume_time" ] && /usr/bin/metrics_client \
-    Power.FirmwareResumeTime"$ac_status" "$firmware_resume_time" 1 10000 50 &
+  ac_status=$(/bin/cat "${power_status_on_suspend}")
+  [ -n "${kernel_suspend_time}" ] && /usr/bin/metrics_client \
+    Power.KernelSuspendTime"${ac_status}" "${kernel_suspend_time}" 1 10000 50 &
+  [ -n "${kernel_resume_time}" ] && /usr/bin/metrics_client \
+    Power.KernelResumeTime"${ac_status}" "${kernel_resume_time}" 1 10000 50 &
+  [ -n "${firmware_resume_time}" ] && /usr/bin/metrics_client \
+    Power.FirmwareResumeTime"${ac_status}" "${firmware_resume_time}" \
+      1 10000 50 &
 
   # Cleanup.
-  /bin/rm -f $power_status_on_suspend
+  /bin/rm -f "${power_status_on_suspend}"
 }
 
 # Find the number of bitfixed chunks
@@ -323,13 +326,13 @@ send_bitfix_metrics() {
   local enable_file="/sys/module/bitfix_snow/parameters/bitfix_enabled"
 
   # Get information about bitfix and send it on.
-  if [ "$(cat $enable_file 2>/dev/null)" = "Y" ]; then
+  if [ "$(cat "${enable_file}" 2>/dev/null)" = "Y" ]; then
     local bitfix_chunks
-    bitfix_chunks=$(get_bitfix_chunks "$recent_messages")
+    bitfix_chunks=$(get_bitfix_chunks "${recent_messages}")
     local bitfix_fixes
-    bitfix_fixes=$(get_bitfix_fixes "$recent_messages")
-    /usr/bin/metrics_client -e Power.BitfixChunks "$bitfix_chunks" 100 &
-    /usr/bin/metrics_client -e Power.BitfixFixes "$bitfix_fixes" 500 &
+    bitfix_fixes=$(get_bitfix_fixes "${recent_messages}")
+    /usr/bin/metrics_client -e Power.BitfixChunks "${bitfix_chunks}" 100 &
+    /usr/bin/metrics_client -e Power.BitfixFixes "${bitfix_fixes}" 500 &
   fi
 }
 
@@ -367,7 +370,7 @@ send_tpschrome_retries() {
   else
     results=$(dmesg | awk -- "${retries_script}")
   fi
-  for result in $results; do
+  for result in ${results}; do
     metric=$(echo "${result}" | cut -d'_' -f1)
     value=$(echo "${result}" | cut -d'_' -f2)
     /usr/bin/metrics_client "${metric}" "${value}" 1 6 7 &
@@ -378,15 +381,15 @@ main() {
   local event="Resume"
   [ "$1" = "-b" ] && event="Boot"
   rm -f "${LAST_RESUME_TIMINGS_FILE}"
-  send_time_in_suspend $event
-  if [ $event = "Resume" ]; then
+  send_time_in_suspend "${event}"
+  if [ "${event}" = "Resume" ]; then
     local recent_messages
     recent_messages=$(split_recent_messages)
-    send_suspend_resume_time "$recent_messages"
-    send_bitfix_metrics "$recent_messages"
-    send_tpschrome_retries "$recent_messages"
+    send_suspend_resume_time "${recent_messages}"
+    send_bitfix_metrics "${recent_messages}"
+    send_tpschrome_retries "${recent_messages}"
 
-    cleanup_recent_messages "$recent_messages"
+    cleanup_recent_messages "${recent_messages}"
   else
     send_tpschrome_retries
   fi
