power: Fix suspend_stress_test shellcheck errors
The script suspend_stress_test currently generates many shellcheck
errors, preventing presubmit hooks from completing successfully.

This CL fixes these errors so CLs modifying this script can be uploaded
without specifying |--ignore-hooks|.

BUG=None
TEST=repo upload
TEST=suspend_stress_test -c 1875 --record_dmesg_dir=/usr/local/agingLogs  --suspend_min=15 --suspend_max=20

Change-Id: Ic3debd391c368930af6fbd49ee28ecccd817bd47
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/4576490
Commit-Queue: Tim Van Patten <timvp@google.com>
Reviewed-by: Eric Caruso <ejcaruso@chromium.org>
Tested-by: Tim Van Patten <timvp@google.com>

diff --git a/power_manager/tools/suspend_stress_test b/power_manager/tools/suspend_stress_test
--- a/power_manager/tools/suspend_stress_test
+++ b/power_manager/tools/suspend_stress_test
@@ -4,7 +4,9 @@
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
-. /usr/share/misc/shflags
+# This file exists on the DUT, but not outside of a chroot during repo upload.
+# shellcheck source=/dev/null
+. "/usr/share/misc/shflags"
 
 DEFINE_integer count 10000 "number of iterations" c
 DEFINE_integer memory_check_size 0 \
@@ -17,19 +19,21 @@ DEFINE_integer suspend_time_margin_min 0 \
                "Min seconds of the (actual - expected) suspended time diff"
 DEFINE_integer wake_max 10 "Max seconds to stay awake for"
 DEFINE_integer wake_min 5 "Min seconds to stay awake for"
-DEFINE_boolean backup_rtc ${FLAGS_FALSE} "Use second rtc if present for backup"
-DEFINE_boolean bug_fatal ${FLAGS_TRUE} "Abort on BUG dmesg lines"
-DEFINE_boolean crc_fatal ${FLAGS_TRUE} "Abort on CRC error dmesg lines"
-DEFINE_boolean warn_fatal ${FLAGS_FALSE} "Abort on WARNING dmesg lines"
-DEFINE_boolean errors_fatal ${FLAGS_TRUE} "Abort on errors"
-DEFINE_boolean fw_errors_fatal ${FLAGS_TRUE} \
+DEFINE_boolean backup_rtc "${FLAGS_FALSE}" \
+               "Use second rtc if present for backup"
+DEFINE_boolean bug_fatal "${FLAGS_TRUE}" "Abort on BUG dmesg lines"
+DEFINE_boolean crc_fatal "${FLAGS_TRUE}" "Abort on CRC error dmesg lines"
+DEFINE_boolean warn_fatal "${FLAGS_FALSE}" "Abort on WARNING dmesg lines"
+DEFINE_boolean errors_fatal "${FLAGS_TRUE}" "Abort on errors"
+DEFINE_boolean fw_errors_fatal "${FLAGS_TRUE}" \
                "Abort on firmware errors (subset of --errors_fatal)"
-DEFINE_boolean premature_wake_fatal ${FLAGS_TRUE} \
+DEFINE_boolean premature_wake_fatal "${FLAGS_TRUE}" \
                "Abort on any premature wakes from suspend"
-DEFINE_boolean late_wake_fatal ${FLAGS_TRUE} \
+DEFINE_boolean late_wake_fatal "${FLAGS_TRUE}" \
                "Abort on any late wakes from suspend"
-DEFINE_boolean memory_check ${FLAGS_FALSE} "Use memory_suspend_test to suspend"
-DEFINE_boolean pm_print_times ${FLAGS_TRUE} \
+DEFINE_boolean memory_check "${FLAGS_FALSE}" \
+               "Use memory_suspend_test to suspend"
+DEFINE_boolean pm_print_times "${FLAGS_TRUE}" \
                "Print the time taken by devices to suspend and resume"
 DEFINE_string  ignore_wakeup_source "none" "Wakeup source to ignore" i
 DEFINE_string  record_dmesg_dir "" "dir to record dmesgs for failed iterations"
@@ -37,29 +41,29 @@ DEFINE_string  pre_suspend_command "" "Command to run before each suspend"
 DEFINE_string  post_resume_command "" "Command to run after each resume"
 
 dmesg_last_cycle() {
-  local lines=0
+  lines=0
 
   lines=$(dmesg | tac | grep -m1 -n "PM: suspend entry" \
             | cut -f1 -d:)
-  dmesg | tail -${lines}
+  dmesg | tail -"${lines}"
 }
 
 # Record the dmesg for the last iteration.
 # Accepts iteration number as an argument (to name the file dmesg_<iter_num>)
 record_dmesg_for_iteration() {
-  local filename=${FLAGS_record_dmesg_dir}/dmesg_$1
+  filename=${FLAGS_record_dmesg_dir}/dmesg_$1
 
-  echo -n " (dmesg > ${filename})..."
-  dmesg_last_cycle > ${filename}
+  printf " (dmesg > %s)..." "${filename}"
+  dmesg_last_cycle > "${filename}"
 }
 
 # Dump STB for AMD Systems for 1st failure.
 record_stb_for_s0ix_error() {
-  local stbFilename=${FLAGS_record_dmesg_dir}/stb_dump
+  stbFilename=${FLAGS_record_dmesg_dir}/stb_dump
 
   if [ -e /sys/kernel/debug/amd_pmc/stb_read ]; then
-    echo -n " (stb > ${stbFilename})..."
-    cat /sys/kernel/debug/amd_pmc/stb_read > ${stbFilename}
+    printf " (stb > %s)..." "${stbFilename}"
+    cat /sys/kernel/debug/amd_pmc/stb_read > "${stbFilename}"
   fi
 }
 
@@ -68,26 +72,26 @@ get_success_count() {
 }
 
 get_ec_resume_result() {
-  local ec_result_path=/sys/kernel/debug/cros_ec/last_resume_result
-  local result=0
+  ec_result_path=/sys/kernel/debug/cros_ec/last_resume_result
+  result=0
   [ -e "${ec_result_path}" ] && result=$(cat "${ec_result_path}")
   printf "%s" "${result}"
 }
 
 # Return the current event count for the wakeup source.
 get_wakeup_source_event_count() {
-  local wakeup_source=$1
-  local event_count=0
+  wakeup_source=$1
+  event_count=0
 
-  if [ "${wakeup_source}" -a "none" != "${wakeup_source}" ]; then
+  if [ -n "${wakeup_source}" ] && [ "none" != "${wakeup_source}" ]; then
     # Get the event count field for the wakeup source.
     event_count=$(awk '$1 == "'"${wakeup_source}"'" { print $3 }' \
                   /sys/kernel/debug/wakeup_sources)
-    if [ -z "$event_count" ]; then
+    if [ -z "${event_count}" ]; then
       event_count=0
     fi
   fi
-  echo "$event_count"
+  echo "${event_count}"
 }
 
 random() {
@@ -95,7 +99,7 @@ random() {
 }
 
 boolean_value() {
-  if [ $1 -eq ${FLAGS_TRUE} ]; then
+  if [ "$1" -eq "${FLAGS_TRUE}" ]; then
     echo "true"
   else
     echo "false"
@@ -166,7 +170,7 @@ get_s2idle_count() {
 }
 
 get_firmware_error_counts() {
-  echo $(cbmem -1 | grep ERROR | wc -l)
+  cbmem -1 | grep -c ERROR
 }
 
 has_ectool_s0ix_counter() {
@@ -187,13 +191,13 @@ if [ "$(id -u)" -ne 0 ]; then
   exit 1
 fi
 
-if [ ${FLAGS_backup_rtc} -eq ${FLAGS_TRUE} ] &&
+if [ "${FLAGS_backup_rtc}" -eq "${FLAGS_TRUE}" ] &&
    [ ! -e /sys/class/rtc/rtc1/wakealarm ]; then
   echo "rtc1 not present, not setting second wakealarm"
   FLAGS_backup_rtc=${FLAGS_FALSE}
 fi
 
-if [ ${FLAGS_memory_check} -eq ${FLAGS_TRUE} ]; then
+if [ "${FLAGS_memory_check}" -eq "${FLAGS_TRUE}" ]; then
   # Default size is set to 0, which tells memory_suspend_test to allocate as
   # much memory as possible.
   suspend_cmd="memory_suspend_test --size=${FLAGS_memory_check_size}"
@@ -202,13 +206,12 @@ else
 fi
 
 if [ -n "${FLAGS_record_dmesg_dir}" ]; then
-  mkdir -p ${FLAGS_record_dmesg_dir}
-  touch ${FLAGS_record_dmesg_dir}/dmesg_test
-  if [ $? -ne 0 ]; then
+  mkdir -p "${FLAGS_record_dmesg_dir}"
+  if ! touch "${FLAGS_record_dmesg_dir}"/dmesg_test; then
     echo "${FLAGS_record_dmesg_dir} not writable for recording dmesg(s)"
     exit 1
   fi
-  rm -rf ${FLAGS_record_dmesg_dir}/dmesg_*
+  rm -rf "${FLAGS_record_dmesg_dir}"/dmesg_*
 fi
 
 check_s0ix_errors=0
@@ -221,32 +224,35 @@ if check_powerd_config --suspend_to_idle; then
   elif has_s2idle; then
     check_s2idle_errors=1
   else
-    echo "Warning! platform uses s0ix/s2idle, but we have no way to verify s0ix/s2idle"
+    echo "Warning! platform uses s0ix/s2idle, but we have no way to verify \
+      s0ix/s2idle"
   fi
 fi
 
-echo "Running ${FLAGS_count} iterations with:"
-echo "  suspend: ${FLAGS_suspend_min}-${FLAGS_suspend_max} seconds"
-echo "  wake: ${FLAGS_wake_min}-${FLAGS_wake_max} seconds"
-echo "  backup_rtc: $(boolean_value ${FLAGS_backup_rtc})"
-echo "  errors_fatal: $(boolean_value ${FLAGS_errors_fatal})"
-echo "  fw_errors_fatal: $(boolean_value ${FLAGS_fw_errors_fatal})"
-echo "  bugs fatal:  $(boolean_value ${FLAGS_bug_fatal})"
-echo "  warnings fatal:  $(boolean_value ${FLAGS_warn_fatal})"
-echo "  crcs fatal:  $(boolean_value ${FLAGS_crc_fatal})"
-echo "  premature wake fatal: $(boolean_value ${FLAGS_premature_wake_fatal})"
-echo "  late wake fatal: $(boolean_value ${FLAGS_late_wake_fatal})"
-echo "  suspend command: ${suspend_cmd}"
-echo "  wakeup source to ignore: ${FLAGS_ignore_wakeup_source}"
-echo "  record_dmesg_dir: ${FLAGS_record_dmesg_dir}"
-echo "  pm_print_times:  $(boolean_value ${FLAGS_pm_print_times})"
+printf "Running %s iterations with:\n" "${FLAGS_count}"
+printf "  suspend: %s-%s seconds\n" \
+       "${FLAGS_suspend_min}" "${FLAGS_suspend_max}"
+printf "  wake: %s-%s seconds\n" "${FLAGS_wake_min}" "${FLAGS_wake_max}"
+printf "  backup_rtc: %s\n" "$(boolean_value "${FLAGS_backup_rtc}")"
+printf "  errors_fatal: %s\n" "$(boolean_value "${FLAGS_errors_fatal}")"
+printf "  fw_errors_fatal: %s\n" "$(boolean_value "${FLAGS_fw_errors_fatal}")"
+printf "  bugs fatal: %s\n" "$(boolean_value "${FLAGS_bug_fatal}")"
+printf "  warnings fatal: %s\n" "$(boolean_value "${FLAGS_warn_fatal}")"
+printf "  crcs fatal: %s\n" "$(boolean_value "${FLAGS_crc_fatal}")"
+printf "  premature wake fatal: %s\n" \
+       "$(boolean_value "${FLAGS_premature_wake_fatal}")"
+printf "  late wake fatal: %s\n" "$(boolean_value "${FLAGS_late_wake_fatal}")"
+printf "  suspend command: %s\n" "${suspend_cmd}"
+printf "  wakeup source to ignore: %s\n" "${FLAGS_ignore_wakeup_source}"
+printf "  record_dmesg_dir: %s\n" "${FLAGS_record_dmesg_dir}"
+printf "  pm_print_times: %s\n" "$(boolean_value "${FLAGS_pm_print_times}")"
 
 initial_successes=$(get_success_count)
 suspend_interval=$(( FLAGS_suspend_max - FLAGS_suspend_min + 1 ))
 wake_interval=$(( FLAGS_wake_max - FLAGS_wake_min + 1 ))
 preserved_pm_print_times=$(cat /sys/power/pm_print_times)
 
-if [ ${FLAGS_pm_print_times} -eq ${FLAGS_TRUE} ]; then
+if [ "${FLAGS_pm_print_times}" -eq "${FLAGS_TRUE}" ]; then
   echo 1 > /sys/power/pm_print_times
 else
   echo 0 > /sys/power/pm_print_times
@@ -287,10 +293,10 @@ while true; do
   last_s0ix_count=$(get_s0ix_count)
   last_s2idle_count=$(get_s2idle_count)
   last_ignore_count=$(get_wakeup_source_event_count \
-                      ${FLAGS_ignore_wakeup_source})
+                      "${FLAGS_ignore_wakeup_source}")
   wakeup_count=$(cat /sys/power/wakeup_count)
   # TODO (harrypan): How to deal with the backup_rtc?
-  if [ ${FLAGS_backup_rtc} -eq ${FLAGS_TRUE} ]; then
+  if [ "${FLAGS_backup_rtc}" -eq "${FLAGS_TRUE}" ]; then
     echo 0 > /sys/class/rtc/rtc1/wakealarm
     echo "+$(( sus_time + 5 ))" > /sys/class/rtc/rtc1/wakealarm
   fi
@@ -303,7 +309,8 @@ while true; do
   fi
 
   start_time="$(cat /sys/class/rtc/rtc0/since_epoch)"
-  ${suspend_cmd} --wakeup_count=${wakeup_count} --suspend_for_sec=${sus_time}
+  ${suspend_cmd} --wakeup_count="${wakeup_count}" \
+    --suspend_for_sec="${sus_time}"
   end_time="$(cat /sys/class/rtc/rtc0/since_epoch)"
 
   if [ -n "${FLAGS_post_resume_command}" ]; then
@@ -316,18 +323,18 @@ while true; do
   actual_sus_time=$(( end_time - start_time ))
   diff_sus_time=$(( actual_sus_time - sus_time ))
   sus_time_str="slept for ${actual_sus_time}s, expected ${sus_time}s"
-  if [ ${diff_sus_time} -lt ${FLAGS_suspend_time_margin_min} ]; then
+  if [ "${diff_sus_time}" -lt "${FLAGS_suspend_time_margin_min}" ]; then
     : $(( premature_wake_count += 1 ))
-    if [ ${FLAGS_premature_wake_fatal} -eq ${FLAGS_TRUE} ]; then
+    if [ "${FLAGS_premature_wake_fatal}" -eq "${FLAGS_TRUE}" ]; then
       echo "Premature wake detected: ${sus_time_str}, test failed."
       exit_loop=1
     else
       echo "Premature wake detected: ${sus_time_str} (ignoring)."
     fi
   fi
-  if [ ${diff_sus_time} -gt ${FLAGS_suspend_time_margin_max} ]; then
+  if [ "${diff_sus_time}" -gt "${FLAGS_suspend_time_margin_max}" ]; then
     : $(( late_wake_count += 1 ))
-    if [ ${FLAGS_late_wake_fatal} -eq ${FLAGS_TRUE} ]; then
+    if [ "${FLAGS_late_wake_fatal}" -eq "${FLAGS_TRUE}" ]; then
       echo "Late wake detected: ${sus_time_str}, test failed."
       exit_loop=1
     else
@@ -339,14 +346,15 @@ while true; do
   # other sources. Although we always clear the wakealarm file before
   # setting it, we still report this error if it is not cleared.
   main_wakealarm="$(cat /sys/class/rtc/rtc0/wakealarm)"
-  if [ -n "${main_wakealarm}" ] && [ ${main_wakealarm} -lt ${end_time} ]; then
+  if [ -n "${main_wakealarm}" ] && \
+     [ "${main_wakealarm}" -lt "${end_time}" ]; then
     : $(( wakealarm_errors += 1 ))
     echo "Wakealarm is not cleared (ignoring)."
   fi
-  if [ ${FLAGS_backup_rtc} -eq ${FLAGS_TRUE} ]; then
+  if [ "${FLAGS_backup_rtc}" -eq "${FLAGS_TRUE}" ]; then
     backup_wakealarm="$(cat /sys/class/rtc/rtc1/wakealarm)"
     if [ -n "${backup_wakealarm}" ] &&
-       [ ${backup_wakealarm} -lt ${end_time} ]; then
+       [ "${backup_wakealarm}" -lt "${end_time}" ]; then
       : $(( wakealarm_errors += 1 ))
       echo "Backup wakealarm is not cleared (ignoring)."
     fi
@@ -354,12 +362,12 @@ while true; do
 
   # Look for errors in firmware log.
   cur_firmware_errors=$(get_firmware_error_counts)
-  number_of_new_errors=$(( ${cur_firmware_errors} - ${last_firmware_errors} ))
-  if [ ${number_of_new_errors} -gt 0 ]; then
+  number_of_new_errors=$(( cur_firmware_errors - last_firmware_errors ))
+  if [ "${number_of_new_errors}" -gt 0 ]; then
     : $(( firmware_errors += 1 ))
-    cbmem -1 | grep ERROR | tail -n ${number_of_new_errors}
-    if [ ${FLAGS_errors_fatal} -eq ${FLAGS_TRUE} -a \
-         ${FLAGS_fw_errors_fatal} -eq ${FLAGS_TRUE} ]; then
+    cbmem -1 | grep ERROR | tail -n "${number_of_new_errors}"
+    if [ "${FLAGS_errors_fatal}" -eq "${FLAGS_TRUE}" ] && \
+       [ "${FLAGS_fw_errors_fatal}" -eq "${FLAGS_TRUE}" ]; then
       exit_loop=1
       echo "Firmware error found."
     else
@@ -370,17 +378,17 @@ while true; do
   # Make sure suspend succeeded
   cur_successes=$(get_success_count)
   cur_ignore_count=$(get_wakeup_source_event_count \
-                     ${FLAGS_ignore_wakeup_source})
+                     "${FLAGS_ignore_wakeup_source}")
   cur_s0ix_count=$(get_s0ix_count)
   cur_s2idle_count=$(get_s2idle_count)
-  if [ ${cur_successes} -eq ${last_successes} -a \
-       ${cur_ignore_count} -eq ${last_ignore_count} ]; then
-    if [ ${FLAGS_errors_fatal} -eq ${FLAGS_TRUE} ]; then
+  if [ "${cur_successes}" -eq "${last_successes}" ] && \
+     [ "${cur_ignore_count}" -eq "${last_ignore_count}" ]; then
+    if [ "${FLAGS_errors_fatal}" -eq "${FLAGS_TRUE}" ]; then
       echo "Suspend failed."
       exit_loop=1
     else
       if [ -n "${FLAGS_record_dmesg_dir}" ]; then
-        record_dmesg_for_iteration ${cur}
+        record_dmesg_for_iteration "${cur}"
       fi
       printf "(suspend failed, ignoring)"
     fi
@@ -388,10 +396,10 @@ while true; do
        [ "${cur_s0ix_count}" = "${last_s0ix_count}" ]; then
     echo "Suspend failed, s0ix count did not increment from ${last_s0ix_count}"
     : $(( s0ix_errors += 1 ))
-    if [ ${FLAGS_errors_fatal} -eq ${FLAGS_TRUE} ]; then
+    if [ "${FLAGS_errors_fatal}" -eq "${FLAGS_TRUE}" ]; then
       exit_loop=1
     elif [ -n "${FLAGS_record_dmesg_dir}" ]; then
-      record_dmesg_for_iteration ${cur}
+      record_dmesg_for_iteration "${cur}"
       if [ "${s0ix_errors}" = 1 ]; then
         record_stb_for_s0ix_error
       fi
@@ -401,10 +409,10 @@ while true; do
     if ! dmesg_last_cycle | grep -q "hwrng: no data available"; then
       echo "Suspend failed, s2idle count did not increment from ${last_s2idle_count}"
       : $(( s2idle_errors += 1 ))
-      if [ ${FLAGS_errors_fatal} -eq ${FLAGS_TRUE} ]; then
+      if [ "${FLAGS_errors_fatal}" -eq "${FLAGS_TRUE}" ]; then
         exit_loop=1
       elif [ -n "${FLAGS_record_dmesg_dir}" ]; then
-        record_dmesg_for_iteration ${cur}
+        record_dmesg_for_iteration "${cur}"
       fi
     else
       # failure caused by hwrng kthread, don't abort (yet), but count the error
@@ -414,10 +422,10 @@ while true; do
     if ! dmesg_last_cycle | grep -q "hwrng: no data available"; then
       echo "EC detected AP suspend error: $(get_ec_resume_result)"
       : $(( ec_suspend_errors += 1 ))
-      if [ ${FLAGS_errors_fatal} -eq ${FLAGS_TRUE} ]; then
+      if [ "${FLAGS_errors_fatal}" -eq "${FLAGS_TRUE}" ]; then
         exit_loop=1
       elif [ -n "${FLAGS_record_dmesg_dir}" ]; then
-        record_dmesg_for_iteration ${cur}
+        record_dmesg_for_iteration "${cur}"
       fi
     else
       # failure caused by hwrng kthread, don't abort (yet), but count the error
@@ -426,11 +434,11 @@ while true; do
   fi
 
   # check hwrng error rate if at least two hwrng related errors were observed
-  if [ ${hwrng_errors} -ge 2 ] && \
-     [ ${FLAGS_errors_fatal} -eq ${FLAGS_TRUE} ]; then
-    hwrng_errors_per_1000=$(( (${hwrng_errors} * 1000) / ${cur} ))
+  if [ "${hwrng_errors}" -ge 2 ] && \
+     [ "${FLAGS_errors_fatal}" -eq "${FLAGS_TRUE}" ]; then
+    hwrng_errors_per_1000=$(( (hwrng_errors * 1000) / cur ))
 
-    if [ ${hwrng_errors_per_1000} -gt 0 ]; then
+    if [ "${hwrng_errors_per_1000}" -gt 0 ]; then
       # rate of suspend failures due to hwrng is >= 1/1000
       echo "Rate of suspend failures caused by hwrng kthread is too high."
       exit_loop=1
@@ -441,26 +449,27 @@ while true; do
   # is not that useful as dmesg will wrap so we would need to account
   # for the count shrinking over time.
   # Exit on BUG
-  if [ ${FLAGS_bug_fatal} -eq ${FLAGS_TRUE} ] &&
+  if [ "${FLAGS_bug_fatal}" -eq "${FLAGS_TRUE}" ] &&
         dmesg | grep -w BUG; then
     echo "BUG found."
     exit_loop=1
   fi
   # Exit on WARNING
-  if [ ${FLAGS_warn_fatal} -eq ${FLAGS_TRUE} ] &&
+  if [ "${FLAGS_warn_fatal}" -eq "${FLAGS_TRUE}" ] &&
         dmesg | grep -w WARNING; then
     echo "WARNING found."
     exit_loop=1
   fi
   # Exit on CRC error
-  if [ ${FLAGS_crc_fatal} -eq ${FLAGS_TRUE} ] && dmesg | grep "CRC.*error"; then
+  if [ "${FLAGS_crc_fatal}" -eq "${FLAGS_TRUE}" ] && \
+     dmesg | grep "CRC.*error"; then
     echo "CRC error found."
     exit_loop=1
   fi
   # Exit the loop if requested from errors or done with iterations
-  if [ ${cur} -eq ${FLAGS_count} ] || [ ${exit_loop} -eq 1 ]; then
-    if [ ${exit_loop} -eq 1 -a -n "${FLAGS_record_dmesg_dir}" ]; then
-      record_dmesg_for_iteration ${cur}
+  if [ "${cur}" -eq "${FLAGS_count}" ] || [ "${exit_loop}" -eq 1 ]; then
+    if [ "${exit_loop}" -eq 1 ] && [ -n "${FLAGS_record_dmesg_dir}" ]; then
+      record_dmesg_for_iteration "${cur}"
       if [ "${s0ix_errors}" = 1 ]; then
         record_stb_for_s0ix_error
       fi
