login: Prevent ui restarts during shutdown/restarts
In several unmount stateful crash reports, we see the following upstart
job status:
...
reboot start/running, process 11461
...
ui start/running, process 13273
...
which indirectly also starts a large number of jobs that depend on
either the starting or started event for ui.

In particular, the ui start/respawn mechanism is handled asynchronously
from the shutdown process: while we have clauses to stop ui when
pre-shutdown starts, there's still a race condition where pre-shutdown
is started while ui-respawn is running. Instead, make sure that
the ui job never triggers either signals if a reboot/shutdown is in
progress.

BUG=b:172343566
TEST=CQ, unittests

Change-Id: If76107b10198bdb010c3b7eb23ff292546cb205b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/3043355
Tested-by: Sarthak Kukreti <sarthakkukreti@chromium.org>
Reviewed-by: Xiyuan Xia <xiyuan@chromium.org>
Reviewed-by: Ryo Hashimoto <hashimoto@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Sarthak Kukreti <sarthakkukreti@chromium.org>

diff --git a/login_manager/init/scripts/ui-pre-start b/login_manager/init/scripts/ui-pre-start
--- a/login_manager/init/scripts/ui-pre-start
+++ b/login_manager/init/scripts/ui-pre-start
@@ -8,6 +8,8 @@ set -e
 
 JOB=$(basename "$0")
 
+DEVICE_SHUTTING_DOWN=4 # Defined in session_manager_service.h
+
 # Read chrome OS configurations
 read_cros_config() {
   local path="$1"
@@ -34,6 +36,17 @@ read_cros_config_int() {
       ;;
     esac
 }
+
+# The ui job can be restarted asynchronously via ui-respawn. This allows the
+# possibility that ui can be started while shutdown/reboot is in process.
+# Make sure that the reboot/halt jobs are not active at the time we are
+# restarting ui.
+if ! initctl status reboot | grep -q 'stop/waiting' || \
+    ! initctl status halt | grep -q 'stop/waiting'; then
+  logger -t "${UPSTART_JOB}" "ERROR: reboot/shutdown in progress, quit."
+  stop ui
+  exit ${DEVICE_SHUTTING_DOWN}
+fi
 
 # Setup drm log tracing if available. This will allow us to access more verbose
 # logs to debug display connectivity issues when they arise. The traces are
