login: Address cros lint errors in ui-pre-start script
go/p2-lint-cleanup aims to clean up lint errors and this CL covers 1
file, login_manager/init/scripts/ui-pre-start.

BUG=b:217670935
TEST=cros lint login_manager/init/scripts/ui-pre-start

Change-Id: Ia26f384e2b9ab1e5b7384f96b5a1de4b41e26bea
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/3899327
Tested-by: Sherri Lin <sherrilin@google.com>
Commit-Queue: Sherri Lin <sherrilin@google.com>
Reviewed-by: Yusuke Sato <yusukes@chromium.org>

diff --git a/login_manager/init/scripts/ui-pre-start b/login_manager/init/scripts/ui-pre-start
--- a/login_manager/init/scripts/ui-pre-start
+++ b/login_manager/init/scripts/ui-pre-start
@@ -16,9 +16,10 @@ is_writeable() {
   local v=0
 
   if [ -f "${file}" ]; then
-    local wfile=$(ls -l "${file}" | awk '$1 ~ /^.*w.*/ { print $NF; }')
+    local wfile
+    wfile=$(find "${file}" -maxdepth 1 | awk '$1 ~ /^.*w.*/ { print $NF; }')
 
-    if [ ! -z "${wfile}" ]; then
+    if [ -n "${wfile}" ]; then
       v=1
     fi
   fi
@@ -37,8 +38,8 @@ read_cros_config() {
 }
 
 read_cros_config_int() {
-  local v=$(read_cros_config "$@")
-
+  local v
+  v=$(read_cros_config "$@")
   # config value should be an integer
   case "${v}" in
     ''|*[!0-9]*)
@@ -59,9 +60,9 @@ read_cros_config_int() {
 # restarting ui.
 if ! initctl status reboot | grep -q 'stop/waiting' || \
     ! initctl status halt | grep -q 'stop/waiting'; then
-  logger -t "${UPSTART_JOB}" "ERROR: reboot/shutdown in progress, quit."
+  logger -t "${UPSTART_JOB:-}" "ERROR: reboot/shutdown in progress, quit."
   stop ui
-  exit ${DEVICE_SHUTTING_DOWN}
+  exit "${DEVICE_SHUTTING_DOWN}"
 fi
 
 # Setup drm log tracing if available. This will allow us to access more verbose
@@ -90,16 +91,16 @@ if [ -w "${DRM_TRACEFS_BUF_SIZE}" ]; then
   echo 64 > "${DRM_TRACEFS_BUF_SIZE}"
 fi
 
-mkdir -p "${UI_LOG_DIR}"
-ln -sf ui.$(date --utc +%Y%m%d-%H%M%S) "${UI_LOG_DIR}/${UI_LOG_FILE}"
+mkdir -p "${UI_LOG_DIR:-}"
+ln -sf ui."$(date --utc +%Y%m%d-%H%M%S)" "${UI_LOG_DIR}/${UI_LOG_FILE:-}"
 
-mkdir -p "${CONTAINER_ROOT_DIR}"
+mkdir -p "${CONTAINER_ROOT_DIR:-}"
 
 # Create a top-level cpu cgroup for ui tasks.  This will be used to share cpu
 # resources with tasks not managed by the UI.  Android will be placed in a
 # parallel cgroup allowing priority to be given to one or the other depending
 # on what the user is doing at the time.
-if [ ! -d "${UI_CPU_CGROUP_DIR}" ]; then
+if [ ! -d "${UI_CPU_CGROUP_DIR:-}" ]; then
   mkdir -p "${UI_CPU_CGROUP_DIR}"
 fi
 
@@ -145,8 +146,9 @@ CPUFREQ_CONF=/etc/cpufreq.conf
 if [ -f "${INPUT_BOOST}" ]; then
   # Default value is 75 for platforms using EAS
   if [ -f "${CPUFREQ_CONF}" ]; then
+    # shellcheck source=/dev/null
     . "${CPUFREQ_CONF}"
-    if [ "${CPUFREQ_GOVERNOR}" = "schedutil" ] || \
+    if [ "${CPUFREQ_GOVERNOR:-}" = "schedutil" ] || \
        [ "${CPUFREQ_GOVERNOR}" = "sched" ]; then
       INPUT_BOOST_DEFAULT=75
     fi
@@ -172,7 +174,7 @@ if [ -d "${CPUSET_NONURGENT_DIR}" ]; then
     fi
     cpus=""
     prefix="${CPUBUSDIR}/cpu"
-    for cpu in ${CPUBUSDIR}/cpu*; do
+    for cpu in "${CPUBUSDIR}"/cpu*; do
       if [ -f "${cpu}/cpu_capacity" ]; then
         cap=$(cat "${cpu}/cpu_capacity")
         if [ "${cap}" -lt "${min_cap}" ]; then
@@ -219,16 +221,16 @@ fi
 
 # Set up the ui freezer cgroup. This is used during suspend to order the
 # freezing of processes to avoid FUSE causing freeze to timeout.
-if [ ! -d ${UI_FREEZER_CGROUP_DIR} ]; then
-  mkdir -p ${UI_FREEZER_CGROUP_DIR}
-  chown -R chronos ${UI_FREEZER_CGROUP_DIR}
-  chown power:power ${UI_FREEZER_CGROUP_DIR}/freezer.state
+if [ ! -d "${UI_FREEZER_CGROUP_DIR:-}" ]; then
+  mkdir -p "${UI_FREEZER_CGROUP_DIR}"
+  chown -R chronos "${UI_FREEZER_CGROUP_DIR}"
+  chown power:power "${UI_FREEZER_CGROUP_DIR}"/freezer.state
 fi
 
 # Set up the renderer freezer.  This is used during the suspend/resume cycle
 # to freeze all the chrome renderers so that they don't take up a lot of power
 # when the system comes up in dark resume
-if [ ! -d "${CHROME_FREEZER_CGROUP_DIR}" ]; then
+if [ ! -d "${CHROME_FREEZER_CGROUP_DIR:-}" ]; then
   mkdir -p "${CHROME_FREEZER_CGROUP_DIR}"
   mkdir -p "${CHROME_FREEZER_CGROUP_DIR}/to_be_frozen"
   chown -R chronos "${CHROME_FREEZER_CGROUP_DIR}"
