installer: Selectively copy A/B miniOS partitions
.. based on key version parsed from flashrom.
This is required as A + B partitions of miniOS will hold miniOS kernels
that vary in signature.

Local test of device chromeos-install'ing onto loopback parted image.
```
          64      262144       9  Label: "MINIOS-A"
                                  Type: ChromeOS miniOS
                                  UUID: 8E793A1A-D8E2-5E4E-8C3C-4880771C4883
    18014329        4096      10  Label: "MINIOS-B"
                                  Type: ChromeOS reserved
                                  UUID: F0C8717A-B098-4944-930A-0DD15BE51DEF

// Copy out exact front bits because older images don't have extended
// partition 10.
localhost # dd if=/dev/loop4p9 of=thisis9 bs=512 count=4096
4096+0 records in
4096+0 records out
2097152 bytes (2.1 MB, 2.0 MiB) copied, 0.0098874 s, 212 MB/s
localhost # dd if=/dev/loop4p10 of=thisis10 bs=512 count=4096
4096+0 records in
4096+0 records out
2097152 bytes (2.1 MB, 2.0 MiB) copied, 0.0148253 s, 141 MB/s

localhost # sha1sum thisis*
7d76d48d64d7ac5411d714a4bb83f37e3e5b8df6  thisis10
7d76d48d64d7ac5411d714a4bb83f37e3e5b8df6  thisis9
```

BUG=b:267545513
TEST=chromeos-install

Change-Id: I3a0e9eb38935dc71bae115bc48bc8bf5e58f5f9a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/4263489
Tested-by: Jae Hoon Kim <kimjae@chromium.org>
Reviewed-by: Yuanpeng Ni‎ <yuanpengni@chromium.org>
Reviewed-by: Julius Werner <jwerner@chromium.org>
Commit-Queue: Jae Hoon Kim <kimjae@chromium.org>

diff --git a/installer/chromeos-install b/installer/chromeos-install
--- a/installer/chromeos-install
+++ b/installer/chromeos-install
@@ -778,6 +778,41 @@ install_stateful() {
   esac
 }
 
+# Retrieves the recovery key version.
+# Default value on failure is "1".
+retrieve_key_version() {
+  local tmpdir="$(mktemp -d)"
+  local tmpflash="${tmpdir}/flash"
+  local tmpflashparsed="${tmpdir}/flashparsed"
+
+  # Suppress failures and fallback to default value.
+  set +e
+
+  # Read the flashrom.
+  flashrom -i GBB:"${tmpflash}" -r >&2
+  if [ "$?" -ne 0 ]; then
+    echo "Failed to read flashrom, defaulting to \"1\"." >&2
+    # Default.
+    echo "1"
+  else
+    # If successful, continue to extract the key version.
+    futility show "${tmpflash}" > "${tmpflashparsed}"
+    local key_version=$(grep -A3 'Recovery Key:' "${tmpflashparsed}" \
+      | grep 'Key Version:' \
+      | grep -Eo '[0-9]+')
+    echo "${key_version}"
+  fi
+
+  # Cleanup tmp files and directory.
+  for p in "${tmpflash}" "${tmpflashparsed}"; do
+    unlink "${p}"
+  done
+  rmdir "${tmpdir}"
+
+  # Back to strict.
+  set -e
+}
+
 # Copy partition from src to dst (figures out partition offsets). Note, this
 # has some special casing for rootfs, kernel, and stateful partitions. In
 # addition, it only copies partitions that are equally sized over one another.
@@ -834,9 +869,15 @@ copy_partition() {
       "${cache_input}"
     ;;
   "${PARTITION_NUM_MINIOS_A}"|"${PARTITION_NUM_MINIOS_B}")
-    # Always copy from MINIOS_A for MiniOS partitions.
-    part_size=$(partsize "${src}" "${PARTITION_NUM_MINIOS_A}")
-    src_offset=$(partoffset "${src}" "${PARTITION_NUM_MINIOS_A}")
+    # Choose to copy from A or B for miniOS partitions.
+    local src_part_num
+    if [ "$(retrieve_key_version)" -eq "1" ]; then
+      src_part_num="${PARTITION_NUM_MINIOS_A}"
+    else
+      src_part_num="${PARTITION_NUM_MINIOS_B}"
+    fi
+    part_size=$(partsize "${src}" "${src_part_num}")
+    src_offset=$(partoffset "${src}" "${src_part_num}")
     write_partition "${part_num}" "${part_size}" "${dst_offset}" \
       "${src_offset}" "${src}" "${dst}" "${chunk_num}" "${total_chunks}" \
       "${cache_input}"
