installer: Remove UBI/UBIFS support
Remove UBI device support and assume root is always on a block device, not
nand (aka mtd) device.

BUG=b:341939848
TEST=CQ

Change-Id: I63ae58ba215d050cd52210ef73333fa1e0f9b7da
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/5567751
Commit-Queue: Gwendal Grignou <gwendal@chromium.org>
Reviewed-by: Jae Hoon Kim <kimjae@chromium.org>
Tested-by: Gwendal Grignou <gwendal@chromium.org>

diff --git a/installer/chromeos-install b/installer/chromeos-install
--- a/installer/chromeos-install
+++ b/installer/chromeos-install
@@ -31,8 +31,6 @@ RECOVERY_KEY_VERSION=
 # Helpful constants.
 HARDWARE_DIAGNOSTICS_PATH=/tmp/hardware_diagnostics.log
 TMPMNT=/tmp/install-mount-point
-# This is defined later once we have mounted the ROOT.
-STATEFUL_FORMAT=
 # Partition numbers that have assumptions about them. This list should be kept
 # to a minimal. Check copy_partition for most special casing.
 
@@ -54,8 +52,6 @@ DEFINE_string payload_image "" "Path to a Chromium OS image to install onto \
 the device's hard drive"
 DEFINE_string pmbr_code "" "Path to PMBR code to be installed"
 DEFINE_string target_bios "" "Bios type to boot with (see postinst --bios)"
-DEFINE_boolean mtd_layout "${FLAGS_FALSE}" "This system uses MTD for \
-partitioning rather than GPT"
 DEFINE_boolean debug "${FLAGS_FALSE}" "Show debug output"
 DEFINE_boolean skip_postinstall "${FLAGS_FALSE}" \
   "Skip postinstall for situations where you're building for a \
@@ -145,7 +141,7 @@ fast_dd() {
 }
 
 # Get the specified env var for the specified partition.
-#  $1 the field name such as "PARTITION_SIZE", "FS_FORMAT"
+#  $1 the field name such as "PARTITION_SIZE", "RESERVED_EBS"
 #  $2 the partition such as "1", or "ROOT_A"
 _get_field() {
   local field part
@@ -154,54 +150,12 @@ _get_field() {
   eval echo \""\${${field}_${part}}"\"
 }
 
-get_format() {
-  _get_field FORMAT "$@"
-}
-
-get_fs_format() {
-  _get_field FS_FORMAT "$@"
-}
-
 get_partition_size() {
   _get_field PARTITION_SIZE "$@"
 }
 
 get_reserved_ebs() {
   _get_field RESERVED_EBS "$@"
-}
-
-# Calculate the maximum number of bad blocks per 1024 blocks for UBI.
-#  $1 partition number
-calculate_max_beb_per_1024() {
-  local part_no mtd_size eb_size nr_blocks
-  part_no="$1"
-  # The max beb per 1024 is on the total device size, not the partition size.
-  mtd_size=$(cat /sys/class/mtd/mtd0/size)
-  eb_size=$(cat /sys/class/mtd/mtd0/erasesize)
-  nr_blocks=$((mtd_size / eb_size))
-  reserved_ebs=$(get_reserved_ebs "${part_no}")
-  echo $((reserved_ebs * 1024 / nr_blocks))
-}
-
-# Format and make UBI volume if it's not already there.
-#  $1 partition number such as "1", "2"
-#  $2 volume name
-init_ubi_volume() {
-  local part_no volume_name phy_ubi log_ubi
-  part_no="$1"
-  volume_name="$2"
-  phy_ubi="/dev/ubi${part_no}"
-  log_ubi="${phy_ubi}_0"
-  if [ ! -e "${phy_ubi}" ]; then
-    ubiformat -y -e 0 "/dev/mtd${part_no}"
-    ubiattach -d "${part_no}" -m "${part_no}" \
-              --max-beb-per1024 "$(calculate_max_beb_per_1024 "${part_no}")"
-  fi
-  if [ ! -e "${log_ubi}" ]; then
-    local volume_size
-    volume_size=$(get_partition_size "${part_no}")
-    ubimkvol -s "${volume_size}" -N "${volume_name}" "${phy_ubi}"
-  fi
 }
 
 # Update a specific partition in the destination device.
@@ -215,7 +169,7 @@ write_partition() {
   local chunk_num="$7"
   local total_chunks="$8"
   local cache_input="$9"
-  local format fs_format src_part_size dst_part_size
+  local src_part_size dst_part_size
 
   if [ "${user_count}" -eq 0 ]; then
     echo "Skipping partition as it does not exist"
@@ -231,93 +185,36 @@ write_partition() {
         "(${dst_part_size})."
   fi
 
-  format="$(get_format "${user_part}")"
-  case ${format} in
-  nand)
-    if [ "${chunk_num}" -ne 1 ]; then
-      return
-    elif [ "${total_chunks}" -ne 1 ]; then
-      echo "Chunking not supported for NAND; will install all in one go"
-    fi
+  # The "dd" command can be used to advise Linux to drop caches and we use
+  # this feature to maximize available cache for future transfers. We deal
+  # with the input and output block devices differently. Here's why:
+  # - For the input block device there are some cases where we know we'll
+  #   want the input to stay in cache (because we're going to use it again)
+  #   and other cases where we know we're done with it. Also note that we
+  #   are likely running from the input block device, so it's good not to
+  #   be too liberal about dropping the cache.
+  # - For the output block we never need the cache kept. We won't be reading
+  #   it again. We can just tell Linux to drop the cache for the whole
+  #   device each time. It should also be noted that it appears most
+  #   efficient not to drop the cache on the output as part of the same "dd"
+  #   doing the transfer (presumably it makes write buffers less efficient).
+  local dd_cache_arg=;
+  # The iflag is unsupported in older versions of "dd".
+  if ! "${cache_input}" && ! "${BUSYBOX_DD_FOUND}"; then
+    dd_cache_arg="iflag=nocache"
+  fi
 
-    flash_erase "/dev/mtd${user_part}" 0 0
-    nandwrite --input-skip $((user_skip * SRC_BLKSIZE)) \
-      --input-size $((user_count * SRC_BLKSIZE)) \
-      "/dev/mtd${user_part}" "${src}"
-    ;;
+  # dd_cache_arg intentionally not quoted to avoid adding empty arg if unset.
+  # shellcheck disable=SC2248
+  fast_dd "${user_count}" "${user_seek}" "${user_skip}" \
+    "${chunk_num}" "${total_chunks}" if="${src}" of="${dst}" conv=notrunc \
+    ${dd_cache_arg}
 
-  ubi)
-    if [ "${chunk_num}" -ne 1 ]; then
-      return
-    elif [ "${total_chunks}" -ne 1 ]; then
-      echo "Chunking not supported for UBI; will install all in one go"
-    fi
-
-    local phy_ubi="/dev/ubi${user_part}"
-    local log_ubi="${phy_ubi}_0"
-    local sysfs_name="/sys/class/mtd/mtd${user_part}/name"
-
-    init_ubi_volume "${user_part}" "$(cat "${sysfs_name}")"
-
-    fs_format="$(get_fs_format "${user_part}")"
-    case ${fs_format} in
-    ubifs)
-      local src_mnt="${TMPMNT}/src" dst_mnt="${TMPMNT}/dst"
-      mkdir -p "${src_mnt}" "${dst_mnt}"
-
-      mkfs.ubifs -y -x none -R 0 "${log_ubi}"
-      mount "${log_ubi}" "${dst_mnt}"
-
-      # Have to copy the files over by hand as the source partition is a
-      # different filesystem type (like ext4).
-      loop_offset_setup "${src}" "${user_seek}" "${SRC_BLKSIZE}"
-      TMPMNT="${src_mnt}" mount_on_loop_dev
-      cp -a "${src_mnt}"/* "${dst_mnt}"/
-      TMPMNT="${src_mnt}" umount_from_loop_dev
-      loop_offset_cleanup
-
-      umount "${log_ubi}"
-      ;;
-    *)
-      ubiupdatevol --skip $((user_skip * SRC_BLKSIZE)) \
-        --size $((user_count * SRC_BLKSIZE)) "${log_ubi}" "${src}"
-      ;;
-    esac
-    ;;
-
-  *)
-    # The "dd" command can be used to advise Linux to drop caches and we use
-    # this feature to maximize available cache for future transfers. We deal
-    # with the input and output block devices differently. Here's why:
-    # - For the input block device there are some cases where we know we'll
-    #   want the input to stay in cache (because we're going to use it again)
-    #   and other cases where we know we're done with it. Also note that we
-    #   are likely running from the input block device, so it's good not to
-    #   be too liberal about dropping the cache.
-    # - For the output block we never need the cache kept. We won't be reading
-    #   it again. We can just tell Linux to drop the cache for the whole
-    #   device each time. It should also be noted that it appears most
-    #   efficient not to drop the cache on the output as part of the same "dd"
-    #   doing the transfer (presumably it makes write buffers less efficient).
-    local dd_cache_arg=;
-    # The iflag is unsupported in older versions of "dd".
-    if ! "${cache_input}" && ! "${BUSYBOX_DD_FOUND}"; then
-      dd_cache_arg="iflag=nocache"
-    fi
-
-    # dd_cache_arg intentionally not quoted to avoid adding empty arg if unset.
-    # shellcheck disable=SC2248
-    fast_dd "${user_count}" "${user_seek}" "${user_skip}" \
-      "${chunk_num}" "${total_chunks}" if="${src}" of="${dst}" conv=notrunc \
-      ${dd_cache_arg}
-
-    # Incantation to advise the kernel to drop cache on the whole dst.
-    #
-    # dd_cache_arg intentionally not quoted to avoid adding empty arg if unset.
-    # shellcheck disable=SC2248
-    dd if="${dst}" ${dd_cache_arg} count=0 status=none
-    ;;
-  esac
+  # Incantation to advise the kernel to drop cache on the whole dst.
+  #
+  # dd_cache_arg intentionally not quoted to avoid adding empty arg if unset.
+  # shellcheck disable=SC2248
+  dd if="${dst}" ${dd_cache_arg} count=0 status=none
 }
 
 # Find root partition of the block device that we are installing from
@@ -532,10 +429,9 @@ check_removable() {
 }
 
 mkfs() {
-  local fs_format="$1"
-  local fs_sector_count="$2"
-  local device="$3"
-  local label="$4"
+  local fs_sector_count="$1"
+  local device="$2"
+  local label="$3"
   # We re-use $@ for our custom options below, so reset it.
   set --
 
@@ -558,45 +454,24 @@ mkfs() {
     num_4k_sectors=$(( fs_sector_count / (sector_size / DST_BLKSIZE) ))
   fi
 
-  # We always make any ext* stateful partitions ext4.
-  case "${fs_format}" in
-  ext[234])
-    mkfs.ext4 -F -b "${sector_size}" -L "${label}" "$@" "${device}" \
-      "${num_4k_sectors}"
-    ;;
-  ubifs)
-    mkfs.ubifs -y -x none -R 0 "/dev/ubi${PARTITION_NUM_STATE}_0"
-    ;;
-  esac
+  mkfs.ext4 -F -b "${sector_size}" -L "${label}" "$@" "${device}" \
+    "${num_4k_sectors}"
 
 }
 
 # Wipes and expands the stateful partition.
 wipe_stateful() {
   echo "Clearing the stateful partition..."
-  local stateful_fs_format
   local vg_name
-  stateful_fs_format="$(get_fs_format "${PARTITION_NUM_STATE}")"
   # state options are stored in $@.
   set --
 
-  case "${STATEFUL_FORMAT}" in
-  ubi)
-    local phy_ubi="/dev/ubi${PARTITION_NUM_STATE}"
-    local log_ubi="${phy_ubi}_0"
-    local sysfs_name="/sys/class/mtd/mtd${PARTITION_NUM_STATE}/name"
-
-    init_ubi_volume "${PARTITION_NUM_STATE}" "$(cat "${sysfs_name}")"
-    ;;
-  *)
-    if [ -b "${DST}" ]; then
-      DEV=$(make_partition_dev "${DST}" "${PARTITION_NUM_STATE}")
-    else
-      loop_offset_setup "${DST}" "${START_STATEFUL}" "${DST_BLKSIZE}"
-      DEV="${LOOP_DEV}"
-    fi
-    ;;
-  esac
+  if [ -b "${DST}" ]; then
+    DEV=$(make_partition_dev "${DST}" "${PARTITION_NUM_STATE}")
+  else
+    loop_offset_setup "${DST}" "${START_STATEFUL}" "${DST_BLKSIZE}"
+  DEV="${LOOP_DEV}"
+  fi
 
   # Zero out the first block of the stateful partition to ensure that
   # mkfs/pvcreate don't get confused by existing state.
@@ -640,21 +515,16 @@ wipe_stateful() {
   # NUM_STATEFUL_SECTORS intentionally not quoted to avoid adding empty arg
   # if unset.
   # shellcheck disable=SC2248
-  mkfs "${stateful_fs_format}" ${NUM_STATEFUL_SECTORS} "${DEV}" "H-STATE"
+  mkfs ${NUM_STATEFUL_SECTORS} "${DEV}" "H-STATE"
 
-  case ${STATEFUL_FORMAT} in
-  ubi) ;;
-  *)
-    # Need to synchronize before releasing loop device, otherwise calling
-    # loop_offset_cleanup may return "device busy" error.
-    sync
-    if [ "${FLAGS_lvm_stateful}" -eq "${FLAGS_TRUE}" ]; then
-      deactivate_volume_group "${vg_name}"
-    elif [ ! -b "${DST}" ]; then
-      loop_offset_cleanup
-    fi
-    ;;
-  esac
+  # Need to synchronize before releasing loop device, otherwise calling
+  # loop_offset_cleanup may return "device busy" error.
+  sync
+  if [ "${FLAGS_lvm_stateful}" -eq "${FLAGS_TRUE}" ]; then
+    deactivate_volume_group "${vg_name}"
+  elif [ ! -b "${DST}" ]; then
+    loop_offset_cleanup
+  fi
 
   # When the stateful partition is wiped the TPM ownership must be reset.
   # This command will not work on Flex devices which do not support it.
@@ -701,23 +571,15 @@ install_stateful() {
   local vg_name
 
   echo "Installing the stateful partition..."
-  case "${STATEFUL_FORMAT}" in
-  ubi)
-    # We modify the global used here as it affects how we unmount later.
-    LOOP_DEV="/dev/ubi${PARTITION_NUM_STATE}_0"
-    ;;
-  *)
-    if [ "${FLAGS_lvm_stateful}" -eq "${FLAGS_TRUE}" ]; then
-      dst_stateful_partition="$(make_partition_dev "${DST}" \
-        "${PARTITION_NUM_STATE}")"
-      vg_name="$(get_volume_group "${dst_stateful_partition}")"
-      vgchange -ay "${vg_name}"
-      LOOP_DEV="/dev/${vg_name}/unencrypted"
-    else
-      loop_offset_setup "${DST}" "${START_STATEFUL}" "${DST_BLKSIZE}"
-    fi
-    ;;
-  esac
+  if [ "${FLAGS_lvm_stateful}" -eq "${FLAGS_TRUE}" ]; then
+    dst_stateful_partition="$(make_partition_dev "${DST}" \
+      "${PARTITION_NUM_STATE}")"
+    vg_name="$(get_volume_group "${dst_stateful_partition}")"
+    vgchange -ay "${vg_name}"
+    LOOP_DEV="/dev/${vg_name}/unencrypted"
+  else
+    loop_offset_setup "${DST}" "${START_STATEFUL}" "${DST_BLKSIZE}"
+  fi
   mount_on_loop_dev rw
 
   # Move log files listed in FLAGS_lab_preserve_logs from stateful_partition to
@@ -821,19 +683,14 @@ install_stateful() {
   done
 
   umount_from_loop_dev
-  case ${STATEFUL_FORMAT} in
-  ubi) ;;
-  *)
-    # Need to synchronize before releasing loop device, otherwise calling
-    # loop_offset_cleanup may return "device busy" error.
-    sync
-    if [ "${FLAGS_lvm_stateful}" -eq "${FLAGS_TRUE}" ]; then
-      deactivate_volume_group "${vg_name}"
-    else
-      loop_offset_cleanup
-    fi
-    ;;
-  esac
+  # Need to synchronize before releasing loop device, otherwise calling
+  # loop_offset_cleanup may return "device busy" error.
+  sync
+  if [ "${FLAGS_lvm_stateful}" -eq "${FLAGS_TRUE}" ]; then
+    deactivate_volume_group "${vg_name}"
+  else
+    loop_offset_cleanup
+  fi
 }
 
 # Get the recovery key version.
@@ -967,41 +824,6 @@ copy_partition() {
   esac
 }
 
-# Remove partitions 1 to 12 from MTD device. Recreate partitions 1 to 12 with
-# information from the current GPT table.
-# $1 is the device node, such as "/dev/mtd0"
-recreate_nand_partitions() {
-  local dst="$1"
-  local blocksize="$2"
-  local part_no
-
-  for part_no in /dev/mtd*; do
-    part_no="$(echo "${part_no}" | cut -b9- | grep '^[0-9]*$' || :)"
-    if [ -z "${part_no}" ] || [ "${part_no}" = "0" ]; then
-      continue
-    fi
-    # Ignore any error in case no UBI volume is attached.
-    ubidetach -m "${part_no}" > /dev/null 2>&1 || true
-    nand_partition del "${dst}" "${part_no}"
-  done
-
-  local gpt_file mtd_size mtd_gpt_file part_size part_offset
-  gpt_file=$(mktemp)
-  flashrom -r "-iRW_GPT:${gpt_file}"
-  mtd_size=$(cat "/sys/class/mtd/$(basename "${dst}")/size")
-  mtd_gpt_file="-D ${mtd_size} ${gpt_file}"
-  for part_no in $(seq "${PARTITION_NUM_STATE}" \
-      "${PARTITION_NUM_EFI_SYSTEM:?}"); do
-    part_size=$(partsize "${mtd_gpt_file}" "${part_no}")
-    : $(( part_size *= blocksize ))
-    part_offset=$(partoffset "${mtd_gpt_file}" "${part_no}")
-    : $(( part_offset *= blocksize ))
-    nand_partition add "${dst}" "${part_no}" \
-      "${part_offset}" "${part_size}"
-  done
-  rm -f "${gpt_file}"
-}
-
 # Find our destination device.
 # If the user hasn't selected a destination,
 # we expect that the disk layout declares it for us.
@@ -1010,14 +832,7 @@ check_dst() {
     die "Error: can not determine destination device. Specify --dst yourself."
   fi
 
-  if [ "${DST}" = "/dev/mtd0" ]; then
-    FLAGS_mtd_layout=${FLAGS_TRUE}
-  fi
-
-  # Check out the dst device.
-  if [ "${FLAGS_mtd_layout}" -eq "${FLAGS_TRUE}" ]; then
-    FLAGS_skip_dst_removable=${FLAGS_TRUE}
-  elif [ ! -b "${DST}" ]; then
+  if [ ! -b "${DST}" ]; then
     die "Error: Unable to find destination block device: ${DST}"
   fi
 
@@ -1034,11 +849,6 @@ get_pmbr_code() {
 
   if [ -n "${FLAGS_pmbr_code}" ]; then
     echo "${FLAGS_pmbr_code}"
-  elif [ "${FLAGS_mtd_layout}" -eq "${FLAGS_TRUE}" ]; then
-    # We don't use PMBR if this is on MTD.
-    dd bs="${DST_BLKSIZE}" \
-      count=1 if=/dev/zero of="${pmbr_code}" >/dev/null 2>&1
-    echo "${pmbr_code}"
   else
     # Steal the PMBR code from the source MBR to put on the dest MBR, for
     # booting on legacy-BIOS devices.
@@ -1050,20 +860,15 @@ get_pmbr_code() {
 # Reload the system partitions after the partition table was modified (so the
 # device nodes like /dev/sda1 can be accessed).
 reload_partitions() {
-  if [ "${FLAGS_mtd_layout}" -eq "${FLAGS_FALSE}" ]; then
-    # Reload the partition table on block devices only.
-    # On MTD, the ChromeOS kernel loads the partition table at boot time.
-    #
-    # In some cases, we may be racing with udev for access to the
-    # device leading to EBUSY when we reread the partition table.  We
-    # avoid the conflict by using `udevadm settle`, so that udev goes
-    # first.  cf. crbug.com/343681.
-    udevadm settle
-    /sbin/blockdev --rereadpt "${DST}"
-  else
-    # On NAND, we need to recreate the partition table.
-    recreate_nand_partitions "${DST}" "${DST_BLKSIZE}"
-  fi
+  # Reload the partition table on block devices only.
+  # On MTD, the ChromeOS kernel loads the partition table at boot time.
+  #
+  # In some cases, we may be racing with udev for access to the
+  # device leading to EBUSY when we reread the partition table.  We
+  # avoid the conflict by using `udevadm settle`, so that udev goes
+  # first.  cf. crbug.com/343681.
+  udevadm settle
+  /sbin/blockdev --rereadpt "${DST}"
 }
 
 # Post partition copying work and special casing
@@ -1079,28 +884,16 @@ do_post_install() {
   # script had better not try to access it, for the reasons we just gave.
   # We can't run this if the target arch isn't the same as the host arch
   if [ "${FLAGS_skip_postinstall}" -eq "${FLAGS_FALSE}" ]; then
-    if [ "${FLAGS_mtd_layout}" -eq "${FLAGS_TRUE}" ]; then
-      if ! [ -b "/dev/ubiblock${PARTITION_NUM_ROOT_A}_0" ]; then
-        ubiblock -c "/dev/ubi${PARTITION_NUM_ROOT_A}_0"
-      fi
-      LOOP_DEV="/dev/ubiblock${PARTITION_NUM_ROOT_A}_0"
-      # We need to pass the __writable__ device to postinst, hence ubiX_0.
-      dst_rootfs_dev="/dev/ubi${PARTITION_NUM_ROOT_A}_0"
+    reload_partitions
+    dst_rootfs_dev="$(make_partition_dev "${DST}" "${PARTITION_NUM_ROOT_A}")"
+    if [ -n "${FLAGS_payload_image}" ]; then
+      loop_offset_setup "${DST}" "${START_ROOTFS_A}" "${DST_BLKSIZE}"
       mount_on_loop_dev
       IS_INSTALL="1" "${TMPMNT}/postinst" "${dst_rootfs_dev}" "$@"
       umount_from_loop_dev
+      loop_offset_cleanup
     else
-      reload_partitions
-      dst_rootfs_dev="$(make_partition_dev "${DST}" "${PARTITION_NUM_ROOT_A}")"
-      if [ -n "${FLAGS_payload_image}" ]; then
-        loop_offset_setup "${DST}" "${START_ROOTFS_A}" "${DST_BLKSIZE}"
-        mount_on_loop_dev
-        IS_INSTALL="1" "${TMPMNT}/postinst" "${dst_rootfs_dev}" "$@"
-        umount_from_loop_dev
-        loop_offset_cleanup
-      else
-        IS_INSTALL="1" "/postinst" "${dst_rootfs_dev}" "$@"
-      fi
+      IS_INSTALL="1" "/postinst" "${dst_rootfs_dev}" "$@"
     fi
   fi
 }
@@ -1177,10 +970,6 @@ main() {
   . "${ROOT}/usr/sbin/write_gpt.sh"
   load_base_vars
 
-  # Now that we have loaded the partition table we can actually read the format
-  # and partition information.
-  STATEFUL_FORMAT="$(get_format "${PARTITION_NUM_STATE}")"
-
   ufs_init
 
   DST=${FLAGS_dst:-$(get_fixed_dst_drive)}
@@ -1216,8 +1005,7 @@ main() {
     fi
   fi
 
-  # Write the GPT using the board specific script. The parameters are ignored
-  # on MTD devices.
+  # Write the GPT using the board specific script.
   if [ "${FLAGS_skip_gpt_creation}" -eq "${FLAGS_FALSE}" ]; then
     write_base_table "${DST}" "$(get_pmbr_code)"
     legacy_offset_size_export "${DST}"
