installer: Attempt vg deactivation in non-strict mode
Otherwise the script bails out on the first error.

BUG=b:326008393
TEST=manual

Change-Id: I5571fdc548e9108d73f81360a83f9c8c1171ebab
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/5492031
Tested-by: Sarthak Kukreti <sarthakkukreti@google.com>
Auto-Submit: Sarthak Kukreti <sarthakkukreti@google.com>
Commit-Queue: Sarthak Kukreti <sarthakkukreti@google.com>
Reviewed-by: Jae Hoon Kim <kimjae@chromium.org>

diff --git a/installer/chromeos-install b/installer/chromeos-install
--- a/installer/chromeos-install
+++ b/installer/chromeos-install
@@ -468,6 +468,9 @@ cleanup_on_failure() {
 }
 
 deactivate_volume_group() {
+  # Suppress failures and fallback to default value.
+  set +e
+
   local vg="${1}"
   local rc=0
   for _ in 1 2 3 4 5 6 7 8 9 10; do
@@ -478,6 +481,10 @@ deactivate_volume_group() {
     fi
     sleep 1
   done
+
+  # Back to strict.
+  set -e
+
   return "${rc}"
 }
 
